# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1200)
        MainWindow.setStyleSheet("QDockWidget {\n"
                                 "    font-weight: bold;\n"
                                 "    font-size: 16pt;\n"
                                 "}\n"
                                 "QDockWidget::title {\n"
                                 "    text-align: left;\n"
                                 "    background: lightblue;\n"
                                 "    padding-left: 15px;\n"
                                 "    padding-top: 5px;\n"
                                 "    padding-bottom: 5px;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.nd_tab = QtWidgets.QWidget()
        self.nd_tab.setObjectName("nd_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.nd_tab)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nb_frame = QtWidgets.QFrame(self.nd_tab)
        self.nb_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nb_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nb_frame.setObjectName("nb_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.nb_frame)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nb_hbox = QtWidgets.QHBoxLayout()
        self.nb_hbox.setSpacing(4)
        self.nb_hbox.setObjectName("nb_hbox")
        self.horizontalLayout.addLayout(self.nb_hbox)
        self.gridLayout_2.addWidget(self.nb_frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.nd_tab, "")
        self.ic_tab = QtWidgets.QWidget()
        self.ic_tab.setObjectName("ic_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ic_tab)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ic_frame = QtWidgets.QFrame(self.ic_tab)
        self.ic_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ic_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ic_frame.setObjectName("ic_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ic_frame)
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ic_hbox = QtWidgets.QHBoxLayout()
        self.ic_hbox.setSpacing(4)
        self.ic_hbox.setObjectName("ic_hbox")
        self.horizontalLayout_2.addLayout(self.ic_hbox)
        self.gridLayout_3.addWidget(self.ic_frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.ic_tab, "")
        self.hmr_tab = QtWidgets.QWidget()
        self.hmr_tab.setObjectName("hmr_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.hmr_tab)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hmr_frame = QtWidgets.QFrame(self.hmr_tab)
        self.hmr_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hmr_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hmr_frame.setObjectName("hmr_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.hmr_frame)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hmr_hbox = QtWidgets.QHBoxLayout()
        self.hmr_hbox.setSpacing(4)
        self.hmr_hbox.setObjectName("hmr_hbox")
        self.horizontalLayout_3.addLayout(self.hmr_hbox)
        self.gridLayout_4.addWidget(self.hmr_frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.hmr_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 32))
        self.menubar.setObjectName("menubar")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addAction(self.actionAboutQt)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionAboutQt.triggered.connect(
            MainWindow.onAboutQt)  # type: ignore
        self.action_About.triggered.connect(MainWindow.onAbout)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nd_tab),
                                  _translate("MainWindow", "ND"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ic_tab),
                                  _translate("MainWindow", "IC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hmr_tab),
                                  _translate("MainWindow", "HMR"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.actionAboutQt.setText(_translate("MainWindow", "About Qt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
