# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QDockWidget {\n"
                                 "    font-weight: bold;\n"
                                 "    font-size: 14pt;\n"
                                 "}\n"
                                 "QDockWidget::title {\n"
                                 "    text-align: left;\n"
                                 "    background: lightblue;\n"
                                 "    padding-left: 15px;\n"
                                 "    padding-top: 5px;\n"
                                 "    padding-bottom: 5px;\n"
                                 "}")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks
                                  | QtWidgets.QMainWindow.AllowTabbedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 32))
        self.menubar.setObjectName("menubar")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(36, 36))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionTake_Snapshot = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tm-icons/snapshot.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTake_Snapshot.setIcon(icon)
        self.actionTake_Snapshot.setObjectName("actionTake_Snapshot")
        self.actionViewSNP = QtWidgets.QAction(MainWindow)
        self.actionViewSNP.setCheckable(True)
        self.actionViewSNP.setChecked(True)
        self.actionViewSNP.setObjectName("actionViewSNP")
        self.actionViewND = QtWidgets.QAction(MainWindow)
        self.actionViewND.setCheckable(True)
        self.actionViewND.setChecked(True)
        self.actionViewND.setObjectName("actionViewND")
        self.actionViewIC = QtWidgets.QAction(MainWindow)
        self.actionViewIC.setCheckable(True)
        self.actionViewIC.setChecked(True)
        self.actionViewIC.setObjectName("actionViewIC")
        self.actionViewHMR = QtWidgets.QAction(MainWindow)
        self.actionViewHMR.setCheckable(True)
        self.actionViewHMR.setChecked(True)
        self.actionViewHMR.setObjectName("actionViewHMR")
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addAction(self.actionAbout_Qt)
        self.menu_View.addAction(self.actionViewSNP)
        self.menu_View.addAction(self.actionViewND)
        self.menu_View.addAction(self.actionViewIC)
        self.menu_View.addAction(self.actionViewHMR)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.actionTake_Snapshot)

        self.retranslateUi(MainWindow)
        self.actionAbout_Qt.triggered.connect(
            MainWindow.onAboutQt)  # type: ignore
        self.action_About.triggered.connect(MainWindow.onAbout)  # type: ignore
        self.actionTake_Snapshot.triggered.connect(
            MainWindow.onTakeSnapshot)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_View.setTitle(_translate("MainWindow", "&View"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionTake_Snapshot.setText(
            _translate("MainWindow", "Take Snapshot"))
        self.actionViewSNP.setText(_translate("MainWindow", "Snapshot Data"))
        self.actionViewND.setText(_translate("MainWindow", "ND Data"))
        self.actionViewIC.setText(_translate("MainWindow", "IC Data"))
        self.actionViewHMR.setText(_translate("MainWindow", "HMR Data"))


from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
