# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_app.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.trajectory_plot = MatplotlibCurveWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.trajectory_plot.setFigureTitleFont(font)
        self.trajectory_plot.setProperty("figureToolbarToggle", False)
        self.trajectory_plot.setObjectName("trajectory_plot")
        self.verticalLayout.addWidget(self.trajectory_plot)
        self.envelope_plot = MatplotlibCurveWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.envelope_plot.setFigureTitleFont(font)
        self.envelope_plot.setProperty("figureToolbarToggle", False)
        self.envelope_plot.setObjectName("envelope_plot")
        self.verticalLayout.addWidget(self.envelope_plot)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.start_btn = QtWidgets.QPushButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icons/start.png"), QtGui.QIcon.Normal,
            QtGui.QIcon.Off)
        self.start_btn.setIcon(icon)
        self.start_btn.setObjectName("start_btn")
        self.gridLayout.addWidget(self.start_btn, 1, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.stop_btn = QtWidgets.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/icons/stop.png"), QtGui.QIcon.Normal,
            QtGui.QIcon.Off)
        self.stop_btn.setIcon(icon1)
        self.stop_btn.setObjectName("stop_btn")
        self.gridLayout.addWidget(self.stop_btn, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.machine_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.machine_lineEdit.setReadOnly(True)
        self.machine_lineEdit.setObjectName("machine_lineEdit")
        self.horizontalLayout_2.addWidget(self.machine_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.segment_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.segment_lineEdit.setReadOnly(True)
        self.segment_lineEdit.setObjectName("segment_lineEdit")
        self.horizontalLayout_2.addWidget(self.segment_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.dtsec_dsbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dtsec_dsbox.setDecimals(1)
        self.dtsec_dsbox.setMinimum(1.0)
        self.dtsec_dsbox.setMaximum(120.0)
        self.dtsec_dsbox.setProperty("value", 2.0)
        self.dtsec_dsbox.setObjectName("dtsec_dsbox")
        self.gridLayout.addWidget(self.dtsec_dsbox, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.latpath_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.latpath_lineEdit.setObjectName("latpath_lineEdit")
        self.horizontalLayout.addWidget(self.latpath_lineEdit)
        self.browse_btn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.browse_btn.sizePolicy().hasHeightForWidth())
        self.browse_btn.setSizePolicy(sizePolicy)
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout.addWidget(self.browse_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.export_btn = QtWidgets.QPushButton(self.groupBox)
        self.export_btn.setObjectName("export_btn")
        self.gridLayout.addWidget(self.export_btn, 0, 5, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 34))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Tools = QtWidgets.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        MainWindow.setMenuBar(self.menubar)
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionE_xit = QtWidgets.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.actionContents = QtWidgets.QAction(MainWindow)
        self.actionContents.setObjectName("actionContents")
        self.actionLoad_Lattice = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/icons/load_lattice.png"), QtGui.QIcon.Normal,
            QtGui.QIcon.Off)
        self.actionLoad_Lattice.setIcon(icon2)
        self.actionLoad_Lattice.setObjectName("actionLoad_Lattice")
        self.menu_File.addAction(self.actionE_xit)
        self.menu_Help.addAction(self.actionContents)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addAction(self.actionAbout_Qt)
        self.menu_Tools.addAction(self.actionLoad_Lattice)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.actionAbout_Qt.triggered.connect(MainWindow.onAboutQt)
        self.actionE_xit.triggered.connect(MainWindow.close)
        self.action_About.triggered.connect(MainWindow.onAbout)
        self.actionLoad_Lattice.triggered.connect(
            MainWindow.onLoadLatticeAction)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Modeling Results"))
        self.trajectory_plot.setFigureTitle(
            _translate("MainWindow", "Central Beam Trajectory"))
        self.envelope_plot.setFigureTitle(
            _translate("MainWindow", "Beam Envelope"))
        self.groupBox.setTitle(_translate("MainWindow", "Online Modeling"))
        self.start_btn.setToolTip(
            _translate("MainWindow", "Start online modeling"))
        self.start_btn.setText(_translate("MainWindow", "START"))
        self.label_2.setText(_translate("MainWindow", "Settling Time"))
        self.label.setText(_translate("MainWindow", "Lattice File to Read"))
        self.stop_btn.setToolTip(
            _translate("MainWindow", "Stop online modeling"))
        self.stop_btn.setText(_translate("MainWindow", "STOP"))
        self.label_3.setText(_translate("MainWindow", "Loaded Configurations"))
        self.label_4.setText(_translate("MainWindow", "Machine"))
        self.label_5.setText(_translate("MainWindow", "Segment"))
        self.dtsec_dsbox.setSuffix(_translate("MainWindow", " Second"))
        self.latpath_lineEdit.setPlaceholderText(
            _translate("MainWindow", "Read initial beam conditions"))
        self.browse_btn.setText(_translate("MainWindow", "Browse"))
        self.export_btn.setToolTip(
            _translate("MainWindow", "Export current FLAME lattice file"))
        self.export_btn.setText(_translate("MainWindow", "Export"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_Tools.setTitle(_translate("MainWindow", "&Tools"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.action_About.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionE_xit.setText(_translate("MainWindow", "E&xit"))
        self.actionE_xit.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionContents.setText(_translate("MainWindow", "Contents"))
        self.actionContents.setShortcut(_translate("MainWindow", "F1"))
        self.actionLoad_Lattice.setText(
            _translate("MainWindow", "Load Lattice"))


from mpl4qt.widgets.mplcurvewidget import MatplotlibCurveWidget
from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
