# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_app.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 975)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.dataviz_modeling = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.dataviz_modeling.sizePolicy().hasHeightForWidth())
        self.dataviz_modeling.setSizePolicy(sizePolicy)
        self.dataviz_modeling.setObjectName("dataviz_modeling")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dataviz_modeling)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.dataviz_modeling)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.trajectory_plot = MatplotlibCurveWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(
            self.trajectory_plot.sizePolicy().hasHeightForWidth())
        self.trajectory_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.trajectory_plot.setFigureTitleFont(font)
        self.trajectory_plot.setProperty("figureToolbarToggle", False)
        self.trajectory_plot.setObjectName("trajectory_plot")
        self.envelope_plot = MatplotlibCurveWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(
            self.envelope_plot.sizePolicy().hasHeightForWidth())
        self.envelope_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.envelope_plot.setFigureTitleFont(font)
        self.envelope_plot.setProperty("figureToolbarToggle", False)
        self.envelope_plot.setObjectName("envelope_plot")
        self.layout_plot = MatplotlibBaseWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.layout_plot.sizePolicy().hasHeightForWidth())
        self.layout_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.layout_plot.setFigureTitleFont(font)
        self.layout_plot.setProperty("figureDPI", 120.0)
        self.layout_plot.setObjectName("layout_plot")
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.dataviz_modeling)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.xmin_lineEdit = QtWidgets.QLineEdit(self.dataviz_modeling)
        self.xmin_lineEdit.setObjectName("xmin_lineEdit")
        self.horizontalLayout_3.addWidget(self.xmin_lineEdit)
        self.label_7 = QtWidgets.QLabel(self.dataviz_modeling)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.xmax_lineEdit = QtWidgets.QLineEdit(self.dataviz_modeling)
        self.xmax_lineEdit.setObjectName("xmax_lineEdit")
        self.horizontalLayout_3.addWidget(self.xmax_lineEdit)
        self.label_8 = QtWidgets.QLabel(self.dataviz_modeling)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.ymin_lineEdit = QtWidgets.QLineEdit(self.dataviz_modeling)
        self.ymin_lineEdit.setObjectName("ymin_lineEdit")
        self.horizontalLayout_3.addWidget(self.ymin_lineEdit)
        self.label_9 = QtWidgets.QLabel(self.dataviz_modeling)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.ymax_lineEdit = QtWidgets.QLineEdit(self.dataviz_modeling)
        self.ymax_lineEdit.setObjectName("ymax_lineEdit")
        self.horizontalLayout_3.addWidget(self.ymax_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.diag_gbox = QtWidgets.QGroupBox(self.splitter)
        self.diag_gbox.setObjectName("diag_gbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.diag_gbox)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.diag_gbox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.select_all_device_btn = QtWidgets.QToolButton(self.diag_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.select_all_device_btn.sizePolicy().hasHeightForWidth())
        self.select_all_device_btn.setSizePolicy(sizePolicy)
        self.select_all_device_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/select-all.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_all_device_btn.setIcon(icon)
        self.select_all_device_btn.setObjectName("select_all_device_btn")
        self.horizontalLayout_8.addWidget(self.select_all_device_btn)
        self.inverse_device_selection_btn = QtWidgets.QToolButton(
            self.diag_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.inverse_device_selection_btn.sizePolicy().hasHeightForWidth())
        self.inverse_device_selection_btn.setSizePolicy(sizePolicy)
        self.inverse_device_selection_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/invert-selection.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inverse_device_selection_btn.setIcon(icon1)
        self.inverse_device_selection_btn.setObjectName(
            "inverse_device_selection_btn")
        self.horizontalLayout_8.addWidget(self.inverse_device_selection_btn)
        self.select_device_btn = QtWidgets.QPushButton(self.diag_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.select_device_btn.sizePolicy().hasHeightForWidth())
        self.select_device_btn.setSizePolicy(sizePolicy)
        self.select_device_btn.setObjectName("select_device_btn")
        self.horizontalLayout_8.addWidget(self.select_device_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.diags_treeView = QtWidgets.QTreeView(self.diag_gbox)
        self.diags_treeView.setObjectName("diags_treeView")
        self.gridLayout_3.addWidget(self.diags_treeView, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        self.config_modeling = QtWidgets.QGroupBox(self.centralwidget)
        self.config_modeling.setObjectName("config_modeling")
        self.gridLayout = QtWidgets.QGridLayout(self.config_modeling)
        self.gridLayout.setContentsMargins(2, 0, 2, 0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.dtsec_dsbox = QtWidgets.QDoubleSpinBox(self.config_modeling)
        self.dtsec_dsbox.setDecimals(1)
        self.dtsec_dsbox.setMinimum(1.0)
        self.dtsec_dsbox.setMaximum(120.0)
        self.dtsec_dsbox.setProperty("value", 2.0)
        self.dtsec_dsbox.setObjectName("dtsec_dsbox")
        self.gridLayout.addWidget(self.dtsec_dsbox, 1, 1, 1, 1)
        self.start_btn = QtWidgets.QPushButton(self.config_modeling)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/start.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.start_btn.setIcon(icon2)
        self.start_btn.setObjectName("start_btn")
        self.gridLayout.addWidget(self.start_btn, 1, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.config_modeling)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.comboBox = QtWidgets.QComboBox(self.config_modeling)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(80, 20,
                                           QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.config_modeling)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.beamstate_from_file_rbtn = QtWidgets.QRadioButton(
            self.config_modeling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.beamstate_from_file_rbtn.sizePolicy().hasHeightForWidth())
        self.beamstate_from_file_rbtn.setSizePolicy(sizePolicy)
        self.beamstate_from_file_rbtn.setObjectName("beamstate_from_file_rbtn")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.beamstate_from_file_rbtn)
        self.horizontalLayout.addWidget(self.beamstate_from_file_rbtn)
        self.latpath_lineEdit = QtWidgets.QLineEdit(self.config_modeling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.latpath_lineEdit.sizePolicy().hasHeightForWidth())
        self.latpath_lineEdit.setSizePolicy(sizePolicy)
        self.latpath_lineEdit.setObjectName("latpath_lineEdit")
        self.horizontalLayout.addWidget(self.latpath_lineEdit)
        self.browse_btn = QtWidgets.QPushButton(self.config_modeling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.browse_btn.sizePolicy().hasHeightForWidth())
        self.browse_btn.setSizePolicy(sizePolicy)
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout.addWidget(self.browse_btn)
        self.beamstate_from_config_rbtn = QtWidgets.QRadioButton(
            self.config_modeling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.beamstate_from_config_rbtn.sizePolicy().hasHeightForWidth())
        self.beamstate_from_config_rbtn.setSizePolicy(sizePolicy)
        self.beamstate_from_config_rbtn.setObjectName(
            "beamstate_from_config_rbtn")
        self.buttonGroup.addButton(self.beamstate_from_config_rbtn)
        self.horizontalLayout.addWidget(self.beamstate_from_config_rbtn)
        self.config_beamstate_btn = QtWidgets.QPushButton(self.config_modeling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.config_beamstate_btn.sizePolicy().hasHeightForWidth())
        self.config_beamstate_btn.setSizePolicy(sizePolicy)
        self.config_beamstate_btn.setObjectName("config_beamstate_btn")
        self.horizontalLayout.addWidget(self.config_beamstate_btn)
        self.show_twiss_btn = QtWidgets.QToolButton(self.config_modeling)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/view-details.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_twiss_btn.setIcon(icon3)
        self.show_twiss_btn.setAutoRaise(True)
        self.show_twiss_btn.setObjectName("show_twiss_btn")
        self.horizontalLayout.addWidget(self.show_twiss_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.stop_btn = QtWidgets.QPushButton(self.config_modeling)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/stop.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.stop_btn.setIcon(icon4)
        self.stop_btn.setObjectName("stop_btn")
        self.gridLayout.addWidget(self.stop_btn, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.config_modeling)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lattice_info_btn = QtWidgets.QToolButton(self.config_modeling)
        self.lattice_info_btn.setIcon(icon3)
        self.lattice_info_btn.setIconSize(QtCore.QSize(24, 24))
        self.lattice_info_btn.setAutoRaise(True)
        self.lattice_info_btn.setObjectName("lattice_info_btn")
        self.horizontalLayout_2.addWidget(self.lattice_info_btn)
        self.label_4 = QtWidgets.QLabel(self.config_modeling)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.machine_lineEdit = QtWidgets.QLineEdit(self.config_modeling)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.machine_lineEdit.setFont(font)
        self.machine_lineEdit.setReadOnly(True)
        self.machine_lineEdit.setObjectName("machine_lineEdit")
        self.horizontalLayout_2.addWidget(self.machine_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.config_modeling)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.segment_lineEdit = QtWidgets.QLineEdit(self.config_modeling)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.segment_lineEdit.setFont(font)
        self.segment_lineEdit.setReadOnly(True)
        self.segment_lineEdit.setObjectName("segment_lineEdit")
        self.horizontalLayout_2.addWidget(self.segment_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.config_modeling)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.export_btn = QtWidgets.QPushButton(self.config_modeling)
        self.export_btn.setObjectName("export_btn")
        self.gridLayout.addWidget(self.export_btn, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.config_modeling)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.config_modeling)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Tools = QtWidgets.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        MainWindow.setMenuBar(self.menubar)
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionE_xit = QtWidgets.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.actionContents = QtWidgets.QAction(MainWindow)
        self.actionContents.setObjectName("actionContents")
        self.actionLoad_Lattice = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/load_lattice.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Lattice.setIcon(icon5)
        self.actionLoad_Lattice.setObjectName("actionLoad_Lattice")
        self.actionSnapshot = QtWidgets.QAction(MainWindow)
        self.actionSnapshot.setObjectName("actionSnapshot")
        self.menu_File.addAction(self.actionE_xit)
        self.menu_Help.addAction(self.actionContents)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addAction(self.actionAbout_Qt)
        self.menu_Tools.addAction(self.actionLoad_Lattice)
        self.menu_Tools.addAction(self.actionSnapshot)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.actionAbout_Qt.triggered.connect(MainWindow.onAboutQt)
        self.actionE_xit.triggered.connect(MainWindow.close)
        self.action_About.triggered.connect(MainWindow.onAbout)
        self.actionLoad_Lattice.triggered.connect(
            MainWindow.onLoadLatticeAction)
        self.actionSnapshot.triggered.connect(MainWindow.onSnapshotAction)
        self.beamstate_from_file_rbtn.toggled['bool'].connect(
            self.latpath_lineEdit.setEnabled)
        self.beamstate_from_file_rbtn.toggled['bool'].connect(
            self.browse_btn.setEnabled)
        self.beamstate_from_config_rbtn.toggled['bool'].connect(
            self.config_beamstate_btn.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dataviz_modeling.setTitle(
            _translate("MainWindow", "Data Visualization"))
        self.trajectory_plot.setFigureTitle(
            _translate("MainWindow", "Central Beam Trajectory"))
        self.envelope_plot.setFigureTitle(
            _translate("MainWindow", "Beam Envelope"))
        self.layout_plot.setFigureXlabel(_translate("MainWindow", "s [m]"))
        self.layout_plot.setFigureTitle(_translate("MainWindow", "Layout"))
        self.label_6.setText(_translate("MainWindow", "x-min"))
        self.label_7.setText(_translate("MainWindow", "x-max"))
        self.label_8.setText(_translate("MainWindow", "y-min"))
        self.label_9.setText(_translate("MainWindow", "y-max"))
        self.diag_gbox.setTitle(_translate("MainWindow", "Diagnostics"))
        self.label_13.setText(_translate("MainWindow", "Devices to Show"))
        self.select_all_device_btn.setToolTip(
            _translate("MainWindow",
                       "<html><head/><body><p>Select All</p></body></html>"))
        self.inverse_device_selection_btn.setToolTip(
            _translate(
                "MainWindow",
                "<html><head/><body><p>Inverse Current Selection</p></body></html>"
            ))
        self.select_device_btn.setText(_translate("MainWindow", "Choose"))
        self.config_modeling.setTitle(
            _translate("MainWindow", "Online Modeling"))
        self.dtsec_dsbox.setSuffix(_translate("MainWindow", " Second"))
        self.start_btn.setToolTip(
            _translate("MainWindow", "Start online modeling"))
        self.start_btn.setText(_translate("MainWindow", "START"))
        self.label_10.setText(_translate("MainWindow", "Model Engine"))
        self.comboBox.setItemText(0, _translate("MainWindow", "FLAME"))
        self.comboBox.setItemText(1, _translate("MainWindow", "TRACK"))
        self.label.setText(_translate("MainWindow", "Initial Beam Conditions"))
        self.beamstate_from_file_rbtn.setText(
            _translate("MainWindow", "From File"))
        self.latpath_lineEdit.setPlaceholderText(
            _translate("MainWindow", "Read from lattice file"))
        self.browse_btn.setText(_translate("MainWindow", "Browse"))
        self.beamstate_from_config_rbtn.setText(
            _translate("MainWindow", "Advanced"))
        self.config_beamstate_btn.setText(_translate("MainWindow",
                                                     "Configure"))
        self.show_twiss_btn.setToolTip(
            _translate("MainWindow", "Show Beam Ellipse"))
        self.show_twiss_btn.setText(_translate("MainWindow", "..."))
        self.stop_btn.setToolTip(
            _translate("MainWindow", "Stop online modeling"))
        self.stop_btn.setText(_translate("MainWindow", "STOP"))
        self.label_2.setText(_translate("MainWindow", "Settling Time"))
        self.lattice_info_btn.setToolTip(
            _translate("MainWindow", "Show Lattice Viewer"))
        self.lattice_info_btn.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Machine"))
        self.label_5.setText(_translate("MainWindow", "Segment"))
        self.label_11.setText(_translate("MainWindow", "Simulation Setup"))
        self.export_btn.setToolTip(
            _translate("MainWindow", "Export current FLAME lattice file"))
        self.export_btn.setText(_translate("MainWindow", "Export"))
        self.label_3.setText(_translate("MainWindow", "Loaded Configurations"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_Tools.setTitle(_translate("MainWindow", "&Tools"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.action_About.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionE_xit.setText(_translate("MainWindow", "E&xit"))
        self.actionE_xit.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionContents.setText(_translate("MainWindow", "Contents"))
        self.actionContents.setShortcut(_translate("MainWindow", "F1"))
        self.actionLoad_Lattice.setText(
            _translate("MainWindow", "Load Lattice"))
        self.actionLoad_Lattice.setShortcut(
            _translate("MainWindow", "Ctrl+Shift+L"))
        self.actionSnapshot.setText(_translate("MainWindow", "Snapshot"))


from mpl4qt.widgets.mplbasewidget import MatplotlibBaseWidget
from mpl4qt.widgets.mplcurvewidget import MatplotlibCurveWidget
from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
