# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_attach.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1075, 839)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.browse_btn = QtWidgets.QPushButton(Dialog)
        self.browse_btn.setObjectName("browse_btn")
        self.gridLayout.addWidget(self.browse_btn, 0, 7, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
                                   "    color: rgb(137, 137, 137);\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 4)
        self.uritype_cbb = QtWidgets.QComboBox(Dialog)
        self.uritype_cbb.setObjectName("uritype_cbb")
        self.uritype_cbb.addItem("")
        self.uritype_cbb.addItem("")
        self.gridLayout.addWidget(self.uritype_cbb, 2, 2, 1, 1)
        self.filetype_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.filetype_lineEdit.setObjectName("filetype_lineEdit")
        self.gridLayout.addWidget(self.filetype_lineEdit, 2, 3, 1, 1)
        self.attach_view = QtWidgets.QTableView(Dialog)
        self.attach_view.setAlternatingRowColors(True)
        self.attach_view.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.attach_view.setObjectName("attach_view")
        self.gridLayout.addWidget(self.attach_view, 4, 1, 1, 7)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.upload_btn = QtWidgets.QPushButton(Dialog)
        self.upload_btn.setObjectName("upload_btn")
        self.gridLayout.addWidget(self.upload_btn, 2, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 5, 1, 1)
        self.attach_btn = QtWidgets.QPushButton(Dialog)
        self.attach_btn.setObjectName("attach_btn")
        self.gridLayout.addWidget(self.attach_btn, 5, 7, 1, 1)
        self.search_btn = QtWidgets.QPushButton(Dialog)
        self.search_btn.setObjectName("search_btn")
        self.gridLayout.addWidget(self.search_btn, 3, 7, 1, 1)
        self.filename_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.filename_lineEdit.setObjectName("filename_lineEdit")
        self.gridLayout.addWidget(self.filename_lineEdit, 2, 6, 1, 1)
        self.filepath_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.filepath_lineEdit.setReadOnly(False)
        self.filepath_lineEdit.setObjectName("filepath_lineEdit")
        self.gridLayout.addWidget(self.filepath_lineEdit, 0, 2, 1, 5)
        self.search_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.gridLayout.addWidget(self.search_lineEdit, 3, 1, 1, 6)
        spacerItem = QtWidgets.QSpacerItem(40, 20,
                                           QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.browse_btn.setText(_translate("Dialog", "Browse"))
        self.label.setText(_translate("Dialog", "Path"))
        self.label_3.setText(_translate("Dialog", "Check and click Attach"))
        self.uritype_cbb.setItemText(0, _translate("Dialog", "File"))
        self.uritype_cbb.setItemText(1, _translate("Dialog", "URL"))
        self.label_2.setText(_translate("Dialog", "Type"))
        self.upload_btn.setText(_translate("Dialog", "Upload"))
        self.label_4.setText(_translate("Dialog", "Name"))
        self.attach_btn.setText(_translate("Dialog", "Attach"))
        self.search_btn.setText(_translate("Dialog", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
