# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_import.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(684, 412)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.filepaths_textEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.filepaths_textEdit.setStyleSheet("QPlainTextEdit {\n"
                                              "    padding: 8px 8px 8px 8px;\n"
                                              "}")
        self.filepaths_textEdit.setReadOnly(True)
        self.filepaths_textEdit.setObjectName("filepaths_textEdit")
        self.gridLayout.addWidget(self.filepaths_textEdit, 1, 0, 1, 4)
        self.browse_btn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.browse_btn.sizePolicy().hasHeightForWidth())
        self.browse_btn.setSizePolicy(sizePolicy)
        self.browse_btn.setObjectName("browse_btn")
        self.gridLayout.addWidget(self.browse_btn, 0, 3, 1, 1)
        self.tags_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.tags_lineEdit.setStyleSheet("QLineEdit {\n"
                                         "    color: blue;\n"
                                         "    padding: 5px 5px 5px 5px;\n"
                                         "}")
        self.tags_lineEdit.setText("")
        self.tags_lineEdit.setObjectName("tags_lineEdit")
        self.gridLayout.addWidget(self.tags_lineEdit, 3, 0, 1, 4)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.import_pb = QtWidgets.QProgressBar(Dialog)
        self.import_pb.setStyleSheet("QProgressBar {\n"
                                     "    border: 1px solid gray;\n"
                                     "    border-radius: 1px;\n"
                                     "    text-align: center;\n"
                                     "}\n"
                                     "\n"
                                     "QProgressBar::chunk {\n"
                                     "    background-color: #05B8CC;\n"
                                     "    width: 10px;\n"
                                     "    margin: 0.5px;\n"
                                     "}")
        self.import_pb.setProperty("value", 0)
        self.import_pb.setObjectName("import_pb")
        self.horizontalLayout.addWidget(self.import_pb)
        spacerItem = QtWidgets.QSpacerItem(20, 20,
                                           QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cancel_btn.sizePolicy().hasHeightForWidth())
        self.cancel_btn.setSizePolicy(sizePolicy)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ok_btn.sizePolicy().hasHeightForWidth())
        self.ok_btn.setSizePolicy(sizePolicy)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 4)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.browse_btn.clicked.connect(Dialog.onOpenFiles)  # type: ignore
        self.cancel_btn.clicked.connect(Dialog.reject)  # type: ignore
        self.ok_btn.clicked.connect(Dialog.onImportSnapshots)  # type: ignore
        self.pushButton.clicked.connect(Dialog.onClearFiles)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(
            _translate("Dialog", "Import the selected files as new snapshots"))
        self.browse_btn.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Choose the data files in CSV or XLSX.</p></body></html>"
            ))
        self.browse_btn.setText(_translate("Dialog", "Browse"))
        self.tags_lineEdit.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Additional tags that added to every snapshot.</p></body></html>"
            ))
        self.label.setText(
            _translate("Dialog", "Additional Tags (separated with ,)"))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
        self.ok_btn.setText(_translate("Dialog", "OK"))
        self.pushButton.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Clear filepaths.</p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
