# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mps_diag.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1230, 600)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("QLabel {\n"
                                 "    margin-bottom: 10px;\n"
                                 "}")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dtype_lbl = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.dtype_lbl.sizePolicy().hasHeightForWidth())
        self.dtype_lbl.setSizePolicy(sizePolicy)
        self.dtype_lbl.setStyleSheet("QLabel {\n"
                                     "    margin-left: 20px;\n"
                                     "    margin-bottom: 10px;\n"
                                     "}")
        self.dtype_lbl.setAlignment(QtCore.Qt.AlignLeading
                                    | QtCore.Qt.AlignLeft
                                    | QtCore.Qt.AlignVCenter)
        self.dtype_lbl.setObjectName("dtype_lbl")
        self.gridLayout.addWidget(self.dtype_lbl, 0, 1, 1, 1)
        self.view = QtWidgets.QTreeView(Form)
        self.view.setStyleSheet(
            "QHeaderView {\n"
            "    qproperty-defaultAlignment: AlignHCenter AlignVCenter;\n"
            "    font-weight: bold;\n"
            "}\n"
            "\n"
            "QTreeView {\n"
            "    font-family: monospace;\n"
            "    show-decoration-selected: 1;\n"
            "    alternate-background-color: #D3D7CF;\n"
            "}\n"
            "\n"
            "QTreeView::item {\n"
            "    /*color: black;*/\n"
            "    border: 1px solid #D9D9D9;\n"
            "    border-top-color: transparent;\n"
            "    border-bottom-color: transparent;\n"
            "}\n"
            "\n"
            "QTreeView::item:hover {\n"
            "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #e7effd, stop: 1 #cbdaf1);\n"
            "    border: 1px solid #bfcde4;\n"
            "}\n"
            "\n"
            "QTreeView::item:selected {\n"
            "    border: 1px solid #567DBC;\n"
            "    background-color: #D3D7CF;\n"
            "}\n"
            "\n"
            "QTreeView::item:selected:active{\n"
            "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #6ea1f1, stop: 1 #567dbc);\n"
            "}")
        self.view.setIndentation(10)
        self.view.setUniformRowHeights(True)
        self.view.setObjectName("view")
        self.gridLayout.addWidget(self.view, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refresh_sts_lbl = QtWidgets.QLabel(Form)
        self.refresh_sts_lbl.setObjectName("refresh_sts_lbl")
        self.horizontalLayout.addWidget(self.refresh_sts_lbl)
        self.auto_width_btn = QtWidgets.QToolButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sm-icons/resize-horizontal.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.auto_width_btn.setIcon(icon)
        self.auto_width_btn.setIconSize(QtCore.QSize(30, 30))
        self.auto_width_btn.setAutoRaise(True)
        self.auto_width_btn.setObjectName("auto_width_btn")
        self.horizontalLayout.addWidget(self.auto_width_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20,
                                           QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.refresh_btn = QtWidgets.QPushButton(Form)
        self.refresh_btn.setCheckable(True)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        self.refresh_rate_dsbox = QtWidgets.QDoubleSpinBox(Form)
        self.refresh_rate_dsbox.setDecimals(1)
        self.refresh_rate_dsbox.setMinimum(0.2)
        self.refresh_rate_dsbox.setMaximum(5.0)
        self.refresh_rate_dsbox.setProperty("value", 1.0)
        self.refresh_rate_dsbox.setObjectName("refresh_rate_dsbox")
        self.horizontalLayout.addWidget(self.refresh_rate_dsbox)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)

        self.retranslateUi(Form)
        self.auto_width_btn.clicked.connect(
            Form.auto_resize_columns)  # type: ignore
        self.refresh_btn.toggled['bool'].connect(
            Form.refreshData)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(
            _translate(
                "Form",
                "<html><head/><body><p><span style=\" font-size:20pt;\">Read-Only Diagnostics MPS Threshold Configurtions</span></p></body></html>"
            ))
        self.dtype_lbl.setText(
            _translate(
                "Form",
                "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#0055ff;\">Device Type</span></p></body></html>"
            ))
        self.refresh_sts_lbl.setText(_translate("Form", "sts"))
        self.auto_width_btn.setToolTip(
            _translate("Form", "Auto adjust column width."))
        self.auto_width_btn.setText(_translate("Form", "Auto Width"))
        self.refresh_btn.setText(_translate("Form", "Refresh"))
        self.refresh_rate_dsbox.setSuffix(_translate("Form", " Hz"))


from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
