# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(857, 542)
        self.gridLayout_9 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_9.setContentsMargins(4, 10, 4, 4)
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.data_tab = QtWidgets.QWidget()
        self.data_tab.setObjectName("data_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.data_tab)
        self.gridLayout.setContentsMargins(4, 10, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.apply_delt_dsbox = QtWidgets.QDoubleSpinBox(self.data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.apply_delt_dsbox.sizePolicy().hasHeightForWidth())
        self.apply_delt_dsbox.setSizePolicy(sizePolicy)
        self.apply_delt_dsbox.setStyleSheet("QDoubleSpinBox {\n"
                                            "    padding-left: 5px;\n"
                                            "}")
        self.apply_delt_dsbox.setDecimals(3)
        self.apply_delt_dsbox.setMaximum(5.0)
        self.apply_delt_dsbox.setSingleStep(0.05)
        self.apply_delt_dsbox.setProperty("value", 0.05)
        self.apply_delt_dsbox.setObjectName("apply_delt_dsbox")
        self.gridLayout.addWidget(self.apply_delt_dsbox, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.data_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.data_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.dbpath_title_lbl = QtWidgets.QLabel(self.data_tab)
        self.dbpath_title_lbl.setAlignment(QtCore.Qt.AlignLeading
                                           | QtCore.Qt.AlignLeft
                                           | QtCore.Qt.AlignVCenter)
        self.dbpath_title_lbl.setObjectName("dbpath_title_lbl")
        self.gridLayout.addWidget(self.dbpath_title_lbl, 6, 0, 1, 1)
        self.ndigit_sbox = QtWidgets.QSpinBox(self.data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ndigit_sbox.sizePolicy().hasHeightForWidth())
        self.ndigit_sbox.setSizePolicy(sizePolicy)
        self.ndigit_sbox.setStyleSheet("QSpinBox {\n"
                                       "    padding-left: 5px;\n"
                                       "}")
        self.ndigit_sbox.setMaximum(20)
        self.ndigit_sbox.setProperty("value", 3)
        self.ndigit_sbox.setObjectName("ndigit_sbox")
        self.gridLayout.addWidget(self.ndigit_sbox, 4, 1, 1, 1)
        self.tol_dsbox = QtWidgets.QDoubleSpinBox(self.data_tab)
        self.tol_dsbox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.tol_dsbox.sizePolicy().hasHeightForWidth())
        self.tol_dsbox.setSizePolicy(sizePolicy)
        self.tol_dsbox.setStyleSheet("QDoubleSpinBox {\n"
                                     "    padding-left: 5px;\n"
                                     "}")
        self.tol_dsbox.setSingleStep(0.1)
        self.tol_dsbox.setProperty("value", 0.1)
        self.tol_dsbox.setObjectName("tol_dsbox")
        self.gridLayout.addWidget(self.tol_dsbox, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40,
                                           QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dbpath_lbl = QtWidgets.QLabel(self.data_tab)
        self.dbpath_lbl.setStyleSheet("QLabel {\n"
                                      "    border: 1px solid gray;\n"
                                      "    background-color: #FFFFFF;\n"
                                      "}")
        self.dbpath_lbl.setText("")
        self.dbpath_lbl.setScaledContents(False)
        self.dbpath_lbl.setWordWrap(True)
        self.dbpath_lbl.setOpenExternalLinks(False)
        self.dbpath_lbl.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextSelectableByMouse)
        self.dbpath_lbl.setObjectName("dbpath_lbl")
        self.horizontalLayout_5.addWidget(self.dbpath_lbl)
        self.dbpath_btn = QtWidgets.QPushButton(self.data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.dbpath_btn.sizePolicy().hasHeightForWidth())
        self.dbpath_btn.setSizePolicy(sizePolicy)
        self.dbpath_btn.setObjectName("dbpath_btn")
        self.horizontalLayout_5.addWidget(self.dbpath_btn)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 1, 1, 1)
        self.dsrc_mode_cbb = QtWidgets.QComboBox(self.data_tab)
        self.dsrc_mode_cbb.setObjectName("dsrc_mode_cbb")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sm-icons/database.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dsrc_mode_cbb.addItem(icon, "")
        self.dsrc_mode_cbb.addItem("")
        self.gridLayout.addWidget(self.dsrc_mode_cbb, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.data_tab)
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
                                | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.wdir_title_lbl = QtWidgets.QLabel(self.data_tab)
        self.wdir_title_lbl.setObjectName("wdir_title_lbl")
        self.gridLayout.addWidget(self.wdir_title_lbl, 8, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wdir_lbl = QtWidgets.QLabel(self.data_tab)
        self.wdir_lbl.setStyleSheet("QLabel {\n"
                                    "    border: 1px solid gray;\n"
                                    "    background-color: #FFFFFF;\n"
                                    "}")
        self.wdir_lbl.setText("")
        self.wdir_lbl.setWordWrap(True)
        self.wdir_lbl.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextSelectableByMouse)
        self.wdir_lbl.setObjectName("wdir_lbl")
        self.horizontalLayout_3.addWidget(self.wdir_lbl)
        self.wdir_btn = QtWidgets.QPushButton(self.data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.wdir_btn.sizePolicy().hasHeightForWidth())
        self.wdir_btn.setSizePolicy(sizePolicy)
        self.wdir_btn.setObjectName("wdir_btn")
        self.horizontalLayout_3.addWidget(self.wdir_btn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 8, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.data_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.tabWidget.addTab(self.data_tab, "")
        self.ms_tab = QtWidgets.QWidget()
        self.ms_tab.setObjectName("ms_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ms_tab)
        self.verticalLayout.setContentsMargins(4, 10, 4, 4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.ms_tab)
        self.plainTextEdit.setStyleSheet(
            "QPlainTextEdit {\n"
            "    border:none;\n"
            "    background-color: rgb(239, 239, 239);\n"
            "}")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.ms_tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.msconf_path_lineEdit = QtWidgets.QLineEdit(self.ms_tab)
        self.msconf_path_lineEdit.setReadOnly(True)
        self.msconf_path_lineEdit.setObjectName("msconf_path_lineEdit")
        self.horizontalLayout_6.addWidget(self.msconf_path_lineEdit)
        self.msconf_open_btn = QtWidgets.QPushButton(self.ms_tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sm-icons/readfile.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.msconf_open_btn.setIcon(icon1)
        self.msconf_open_btn.setObjectName("msconf_open_btn")
        self.horizontalLayout_6.addWidget(self.msconf_open_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.groupBox = QtWidgets.QGroupBox(self.ms_tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.msconf_rate_cbb = QtWidgets.QComboBox(self.groupBox)
        self.msconf_rate_cbb.setEditable(True)
        self.msconf_rate_cbb.setObjectName("msconf_rate_cbb")
        self.msconf_rate_cbb.addItem("")
        self.msconf_rate_cbb.addItem("")
        self.horizontalLayout_4.addWidget(self.msconf_rate_cbb)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.msconf_nshot_cbb = QtWidgets.QComboBox(self.groupBox)
        self.msconf_nshot_cbb.setEditable(True)
        self.msconf_nshot_cbb.setObjectName("msconf_nshot_cbb")
        self.msconf_nshot_cbb.addItem("")
        self.msconf_nshot_cbb.addItem("")
        self.msconf_nshot_cbb.addItem("")
        self.horizontalLayout_4.addWidget(self.msconf_nshot_cbb)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.tabWidget.addTab(self.ms_tab, "")
        self.view_tab = QtWidgets.QWidget()
        self.view_tab.setObjectName("view_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.view_tab)
        self.gridLayout_2.setContentsMargins(4, 10, 4, 4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.view_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.view_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.font_sample_lbl = QtWidgets.QLabel(self.view_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.font_sample_lbl.sizePolicy().hasHeightForWidth())
        self.font_sample_lbl.setSizePolicy(sizePolicy)
        self.font_sample_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.font_sample_lbl.setObjectName("font_sample_lbl")
        self.horizontalLayout_2.addWidget(self.font_sample_lbl)
        self.select_font_btn = QtWidgets.QPushButton(self.view_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.select_font_btn.sizePolicy().hasHeightForWidth())
        self.select_font_btn.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sm-icons/choose-font.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_font_btn.setIcon(icon2)
        self.select_font_btn.setObjectName("select_font_btn")
        self.horizontalLayout_2.addWidget(self.select_font_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.col_visibility_gbox = QtWidgets.QGridLayout()
        self.col_visibility_gbox.setSpacing(6)
        self.col_visibility_gbox.setObjectName("col_visibility_gbox")
        self.gridLayout_2.addLayout(self.col_visibility_gbox, 2, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.tabWidget.addTab(self.view_tab, "")
        self.config_tab = QtWidgets.QWidget()
        self.config_tab.setObjectName("config_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.config_tab)
        self.gridLayout_3.setContentsMargins(4, 10, 4, 4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.config_tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.reset_app_config_btn = QtWidgets.QPushButton(self.config_tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/sm-icons/refresh.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset_app_config_btn.setIcon(icon3)
        self.reset_app_config_btn.setObjectName("reset_app_config_btn")
        self.gridLayout_3.addWidget(self.reset_app_config_btn, 1, 3, 1, 1)
        self.config_btns_hbox = QtWidgets.QHBoxLayout()
        self.config_btns_hbox.setContentsMargins(-1, 0, -1, -1)
        self.config_btns_hbox.setSpacing(4)
        self.config_btns_hbox.setObjectName("config_btns_hbox")
        self.gridLayout_3.addLayout(self.config_btns_hbox, 4, 0, 1, 5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 5, 0, 1, 1)
        self.view_app_config_btn = QtWidgets.QPushButton(self.config_tab)
        self.view_app_config_btn.setIcon(icon1)
        self.view_app_config_btn.setObjectName("view_app_config_btn")
        self.gridLayout_3.addWidget(self.view_app_config_btn, 1, 2, 1, 1)
        self.appconf_path_lineEdit = QtWidgets.QLineEdit(self.config_tab)
        self.appconf_path_lineEdit.setReadOnly(True)
        self.appconf_path_lineEdit.setObjectName("appconf_path_lineEdit")
        self.gridLayout_3.addWidget(self.appconf_path_lineEdit, 1, 1, 1, 1)
        self.export_app_config_btn = QtWidgets.QPushButton(self.config_tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/sm-icons/save.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_app_config_btn.setIcon(icon4)
        self.export_app_config_btn.setObjectName("export_app_config_btn")
        self.gridLayout_3.addWidget(self.export_app_config_btn, 1, 4, 1, 1)
        self.tabWidget.addTab(self.config_tab, "")
        self.adv_tab = QtWidgets.QWidget()
        self.adv_tab.setObjectName("adv_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.adv_tab)
        self.gridLayout_6.setContentsMargins(4, 10, 4, 4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.adv_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setContentsMargins(4, 10, 4, 4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_73 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
                                   | QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_5.addWidget(self.label_73, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.model_rbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.model_rbtn.setEnabled(False)
        self.model_rbtn.setChecked(True)
        self.model_rbtn.setObjectName("model_rbtn")
        self.horizontalLayout.addWidget(self.model_rbtn)
        self.live_rbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.live_rbtn.setEnabled(False)
        self.live_rbtn.setChecked(False)
        self.live_rbtn.setObjectName("live_rbtn")
        self.horizontalLayout.addWidget(self.live_rbtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.init_snp_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.init_snp_btn.setObjectName("init_snp_btn")
        self.gridLayout_5.addWidget(self.init_snp_btn, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.adv_tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(3, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 1, 1, 1, 1)
        self.skip_none_chkbox = QtWidgets.QCheckBox(self.adv_tab)
        self.skip_none_chkbox.setObjectName("skip_none_chkbox")
        self.gridLayout_6.addWidget(self.skip_none_chkbox, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 2, 0, 1, 1)
        self.tabWidget.addTab(self.adv_tab, "")
        self.gridLayout_9.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20,
                                            QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout_12.addWidget(self.ok_btn)
        self.gridLayout_9.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.ok_btn.clicked.connect(Dialog.on_click_ok)  # type: ignore
        self.select_font_btn.clicked.connect(
            Dialog.on_select_font)  # type: ignore
        self.wdir_btn.clicked.connect(Dialog.on_choose_wdir)  # type: ignore
        self.dbpath_btn.clicked.connect(
            Dialog.on_choose_dbfile)  # type: ignore
        self.model_rbtn.toggled['bool'].connect(
            Dialog.on_toggle_mode)  # type: ignore
        self.live_rbtn.toggled['bool'].connect(
            Dialog.on_toggle_mode)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.apply_delt_dsbox.setSuffix(_translate("Dialog", " seconds"))
        self.label_3.setText(_translate("Dialog", "Data source type"))
        self.label_2.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Discrepancy between set and read.</p></body></html>"
            ))
        self.label_2.setText(
            _translate("Dialog", "Allowed absolute discrepancy"))
        self.dbpath_title_lbl.setText(_translate("Dialog", "Database path"))
        self.tol_dsbox.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Use <span style=\" font-style:italic;\">Tolerance</span> column to adjust the values, they are being managed with PVs now.</p></body></html>"
            ))
        self.dbpath_btn.setText(_translate("Dialog", "Browse"))
        self.dsrc_mode_cbb.setItemText(0, _translate("Dialog", "database"))
        self.dsrc_mode_cbb.setItemText(1, _translate("Dialog", "file"))
        self.label.setText(
            _translate("Dialog", "Time wait for batch settings apply"))
        self.wdir_title_lbl.setText(_translate("Dialog", "Working directory"))
        self.wdir_btn.setText(_translate("Dialog", "Browse"))
        self.label_4.setText(_translate("Dialog", "Float number precision"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data_tab),
                                  _translate("Dialog", "Data"))
        self.plainTextEdit.setPlainText(
            _translate(
                "Dialog",
                "The configuration file for machine state capturing is maintained at one single location, changing it will affect all machine state fetching thereafter.\n"
                "\n"
                "If you\'d like to use a customized version, just copy and modify this file, and edit it in the app configuration file of Settings Manager."
            ))
        self.label_11.setText(_translate("Dialog", "Configfile in use"))
        self.msconf_open_btn.setText(_translate("Dialog", "Read"))
        self.groupBox.setTitle(
            _translate("Dialog", "DAQ (Runtime Configurable)"))
        self.label_8.setText(_translate("Dialog", "Rate"))
        self.msconf_rate_cbb.setItemText(0, _translate("Dialog", "1"))
        self.msconf_rate_cbb.setItemText(1, _translate("Dialog", "5"))
        self.label_9.setText(_translate("Dialog", "Hz"))
        self.label_10.setText(_translate("Dialog", "Total # of Shots"))
        self.msconf_nshot_cbb.setItemText(0, _translate("Dialog", "5"))
        self.msconf_nshot_cbb.setItemText(1, _translate("Dialog", "10"))
        self.msconf_nshot_cbb.setItemText(2, _translate("Dialog", "20"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ms_tab),
                                  _translate("Dialog", "Machine State"))
        self.label_5.setText(
            _translate(
                "Dialog",
                "Check the button to hide the named column, uncheck to show."))
        self.label_6.setText(_translate("Dialog", "Font"))
        self.font_sample_lbl.setText(_translate("Dialog", "Sample"))
        self.select_font_btn.setToolTip(
            _translate("Dialog", "Select display font."))
        self.select_font_btn.setText(_translate("Dialog", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.view_tab),
                                  _translate("Dialog", "Settings View"))
        self.label_7.setText(_translate("Dialog", "Configfile in use"))
        self.reset_app_config_btn.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Reset with default app configurations.</p></body></html>"
            ))
        self.reset_app_config_btn.setText(_translate("Dialog", "Reset"))
        self.view_app_config_btn.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Read the original app configurations in the Text Editor.</p></body></html>"
            ))
        self.view_app_config_btn.setText(_translate("Dialog", "Read"))
        self.export_app_config_btn.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Export the current app configurations with all the runtime adjustments to a file.</p></body></html>"
            ))
        self.export_app_config_btn.setText(_translate("Dialog", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_tab),
                                  _translate("Dialog", "App Configs"))
        self.groupBox_2.setTitle(
            _translate(
                "Dialog",
                "Snapshot Initialization (Create a snapshot from the loaded lattice)"
            ))
        self.label_73.setText(_translate("Dialog",
                                         "Initial field values from"))
        self.model_rbtn.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Initialize field set value from pre-defined \'model\' environment, which is maintained by \'phantasy-machines\' package.</p></body></html>"
            ))
        self.model_rbtn.setText(_translate("Dialog", "Model"))
        self.live_rbtn.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Initialize field set value by pulling the live device settings from controls network.</p></body></html>"
            ))
        self.live_rbtn.setText(_translate("Dialog", "Live"))
        self.init_snp_btn.setText(_translate("Dialog", "Initialize"))
        self.label_12.setText(
            _translate("Dialog", "Whether show non-reachable device settings"))
        self.skip_none_chkbox.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>Skip devices that are not reachable (when initializing with loaded lattice).</p></body></html>"
            ))
        self.skip_none_chkbox.setText(
            _translate("Dialog", "Skip Non-Reachables"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.adv_tab),
                                  _translate("Dialog", "Advanced"))
        self.ok_btn.setText(_translate("Dialog", "OK"))


from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
