# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_post_snp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(916, 622)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(6, 8, 6, 6)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.on_template_rbtn = QtWidgets.QRadioButton(Dialog)
        self.on_template_rbtn.setObjectName("on_template_rbtn")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.on_template_rbtn)
        self.gridLayout.addWidget(self.on_template_rbtn, 3, 0, 1, 1)
        self.tags_area = QtWidgets.QScrollArea(Dialog)
        self.tags_area.setWidgetResizable(True)
        self.tags_area.setObjectName("tags_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 902, 89))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tags_area.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.tags_area, 7, 0, 1, 3)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
                                | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
                                         "    color: gray;\n"
                                         "}")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 5, 0, 1, 3)
        self.selected_tags = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.selected_tags.sizePolicy().hasHeightForWidth())
        self.selected_tags.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.selected_tags.setFont(font)
        self.selected_tags.setStyleSheet(
            "QLabel {\n"
            "    color: rgb(0, 123, 255);\n"
            "    background-color: rgb(233, 233, 233);\n"
            "}")
        self.selected_tags.setText("")
        self.selected_tags.setObjectName("selected_tags")
        self.gridLayout.addWidget(self.selected_tags, 6, 1, 1, 2)
        self.beamSpeciesDisplayWidget = BeamSpeciesDisplayWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.beamSpeciesDisplayWidget.sizePolicy().hasHeightForWidth())
        self.beamSpeciesDisplayWidget.setSizePolicy(sizePolicy)
        self.beamSpeciesDisplayWidget.setProperty("expanded", True)
        self.beamSpeciesDisplayWidget.setProperty(
            "allowClickingIonSourceButtons", False)
        self.beamSpeciesDisplayWidget.setObjectName("beamSpeciesDisplayWidget")
        self.gridLayout.addWidget(self.beamSpeciesDisplayWidget, 1, 2, 3, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20,
                                           QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 10, 0, 1, 3)
        self.orig_template_lbl = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.orig_template_lbl.sizePolicy().hasHeightForWidth())
        self.orig_template_lbl.setSizePolicy(sizePolicy)
        self.orig_template_lbl.setStyleSheet("QLabel {\n"
                                             "    color: #D81B60;\n"
                                             "    border: 1px solid gray;\n"
                                             "    padding: 2px 5px 2px 5px; \n"
                                             "}")
        self.orig_template_lbl.setAlignment(QtCore.Qt.AlignLeading
                                            | QtCore.Qt.AlignLeft
                                            | QtCore.Qt.AlignVCenter)
        self.orig_template_lbl.setObjectName("orig_template_lbl")
        self.gridLayout.addWidget(self.orig_template_lbl, 1, 1, 1, 1)
        self.note_textEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.note_textEdit.setStyleSheet("QPlainTextEdit {\n"
                                         "    color: rgb(0, 123, 255);\n"
                                         "}")
        self.note_textEdit.setObjectName("note_textEdit")
        self.gridLayout.addWidget(self.note_textEdit, 9, 0, 1, 3)
        self.on_loaded_rbtn = QtWidgets.QRadioButton(Dialog)
        self.on_loaded_rbtn.setChecked(True)
        self.on_loaded_rbtn.setObjectName("on_loaded_rbtn")
        self.buttonGroup.addButton(self.on_loaded_rbtn)
        self.gridLayout.addWidget(self.on_loaded_rbtn, 1, 0, 1, 1)
        self.template_area = QtWidgets.QScrollArea(Dialog)
        self.template_area.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.template_area.sizePolicy().hasHeightForWidth())
        self.template_area.setSizePolicy(sizePolicy)
        self.template_area.setWidgetResizable(True)
        self.template_area.setObjectName("template_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(
            0, 0, 902, 89))
        self.scrollAreaWidgetContents_2.setObjectName(
            "scrollAreaWidgetContents_2")
        self.template_area.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.template_area, 4, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
                                   "    border-top: 0px solid gray;\n"
                                   "    border-bottom: 1px solid gray;\n"
                                   "    padding: 2px 0px 5px 0px;\n"
                                   "}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 3)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.on_click_ok)  # type: ignore
        self.pushButton_2.clicked.connect(
            Dialog.on_click_cancel)  # type: ignore
        self.on_template_rbtn.toggled['bool'].connect(
            self.template_area.setEnabled)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.on_loaded_rbtn)
        Dialog.setTabOrder(self.on_loaded_rbtn, self.on_template_rbtn)
        Dialog.setTabOrder(self.on_template_rbtn, self.template_area)
        Dialog.setTabOrder(self.template_area, self.tags_area)
        Dialog.setTabOrder(self.tags_area, self.note_textEdit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.on_template_rbtn.setText(_translate("Dialog", "On A Template"))
        self.label.setText(_translate("Dialog", "Note"))
        self.label_5.setText(_translate("Dialog", "(the checked one)"))
        self.plainTextEdit.setPlainText(
            _translate(
                "Dialog",
                "By default, the one matches the machine operations is checked, if not, meaning the loaded one is not originated from any."
            ))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.orig_template_lbl.setToolTip(
            _translate(
                "Dialog",
                "<html><head/><body><p>The originated snapshot template.</p></body></html>"
            ))
        self.orig_template_lbl.setText(
            _translate("Dialog", "originated template"))
        self.note_textEdit.setPlaceholderText(
            _translate("Dialog", "Input note ..."))
        self.on_loaded_rbtn.setText(_translate("Dialog",
                                               "On Currently Loaded"))
        self.label_2.setText(_translate("Dialog", "Tags"))
        self.label_4.setText(_translate("Dialog", "Create a New Snapshot"))


from phantasy_ui.widgets.beam_species_displayWidget import BeamSpeciesDisplayWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
