# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_snpdiff.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1210, 836)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.enable_reldiff_rbtn = QtWidgets.QRadioButton(self.groupBox)
        self.enable_reldiff_rbtn.setObjectName("enable_reldiff_rbtn")
        self.diff_level_rgrp = QtWidgets.QButtonGroup(Form)
        self.diff_level_rgrp.setObjectName("diff_level_rgrp")
        self.diff_level_rgrp.addButton(self.enable_reldiff_rbtn)
        self.gridLayout_2.addWidget(self.enable_reldiff_rbtn, 0, 0, 1, 1)
        self.absdiff_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.absdiff_lineEdit.setObjectName("absdiff_lineEdit")
        self.gridLayout_2.addWidget(self.absdiff_lineEdit, 1, 1, 1, 1)
        self.reldiff_sbox = QtWidgets.QSpinBox(self.groupBox)
        self.reldiff_sbox.setObjectName("reldiff_sbox")
        self.gridLayout_2.addWidget(self.reldiff_sbox, 0, 1, 1, 1)
        self.enable_absdiff_rbtn = QtWidgets.QRadioButton(self.groupBox)
        self.enable_absdiff_rbtn.setObjectName("enable_absdiff_rbtn")
        self.diff_level_rgrp.addButton(self.enable_absdiff_rbtn)
        self.gridLayout_2.addWidget(self.enable_absdiff_rbtn, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.show_outrange_rbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.show_outrange_rbtn.setObjectName("show_outrange_rbtn")
        self.show_opt_rgrp = QtWidgets.QButtonGroup(Form)
        self.show_opt_rgrp.setObjectName("show_opt_rgrp")
        self.show_opt_rgrp.addButton(self.show_outrange_rbtn)
        self.gridLayout_3.addWidget(self.show_outrange_rbtn, 0, 0, 1, 1)
        self.show_inrange_rbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.show_inrange_rbtn.setObjectName("show_inrange_rbtn")
        self.show_opt_rgrp.addButton(self.show_inrange_rbtn)
        self.gridLayout_3.addWidget(self.show_inrange_rbtn, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 3, 1, 1, 1)
        self.snpdiffView = QtWidgets.QTableView(Form)
        self.snpdiffView.setObjectName("snpdiffView")
        self.gridLayout.addWidget(self.snpdiffView, 2, 0, 1, 2)
        self.snps_hbox = QtWidgets.QHBoxLayout()
        self.snps_hbox.setObjectName("snps_hbox")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("monospace")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
                                   "    font-family: monospace;\n"
                                   "    font-size: 8pt;\n"
                                   "    color: #888A85;\n"
                                   "}")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.snp_one_name_lbl = QtWidgets.QLabel(Form)
        self.snp_one_name_lbl.setStyleSheet("QLabel {\n"
                                            "    font-family: monospace;\n"
                                            "}")
        self.snp_one_name_lbl.setObjectName("snp_one_name_lbl")
        self.verticalLayout.addWidget(self.snp_one_name_lbl)
        self.snps_hbox.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("monospace")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
                                   "    font-family: monospace;\n"
                                   "    font-size: 8pt;\n"
                                   "    color: #888A85;\n"
                                   "}")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.snp_two_name_lbl = QtWidgets.QLabel(Form)
        self.snp_two_name_lbl.setStyleSheet("QLabel {\n"
                                            "    font-family: monospace;\n"
                                            "}")
        self.snp_two_name_lbl.setObjectName("snp_two_name_lbl")
        self.verticalLayout_2.addWidget(self.snp_two_name_lbl)
        self.snps_hbox.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.snps_hbox, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Discrenpancy Level"))
        self.enable_reldiff_rbtn.setText(
            _translate("Form", "By relative diff |Δx/x1|"))
        self.absdiff_lineEdit.setText(_translate("Form", "0.000"))
        self.reldiff_sbox.setSuffix(_translate("Form", " %"))
        self.enable_absdiff_rbtn.setText(
            _translate("Form", "By absolute diff |Δx|"))
        self.groupBox_2.setTitle(_translate("Form", "Filters"))
        self.show_outrange_rbtn.setToolTip(
            _translate(
                "Form",
                "<html><head/><body><p>Show items beyond defined discrenpancy level.</p></body></html>"
            ))
        self.show_outrange_rbtn.setText(_translate("Form",
                                                   "Beyond diff range"))
        self.show_inrange_rbtn.setToolTip(
            _translate(
                "Form",
                "<html><head/><body><p>Show items within defined discrenpancy level.</p></body></html>"
            ))
        self.show_inrange_rbtn.setText(_translate("Form",
                                                  "Between diff range"))
        self.label_6.setText(_translate("Form", "Snapshot 1"))
        self.snp_one_name_lbl.setText(
            _translate("Form", "2023-12-13T01:49:41 - 86Kr36(19+)"))
        self.label_7.setText(_translate("Form", "Snapshot 2"))
        self.snp_two_name_lbl.setText(
            _translate("Form", "2023-12-13T01:49:41 - 86Kr36(19+)"))
        self.label.setText(_translate("Form",
                                      "<h2>Compare Two Snapshots</h2>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
