# Field-of-interest per element type for settings view
# Define ENG and PHY fields in pair
# key name could be element type and element name (higher priority)

[DEFAULT]
fields = ['I', 'V', 'TM', 'B', 'B2', 'B3', 'VOLT']

[CAV]
fields = ['PHA', 'AMP', 'PHASE', 'AMPLITUDE',
          'PHA_CREST', 'PHASE_CREST', 'AMP_COEF', 'AMPLITUDE_COEF',
]

["FE_LEBT:CAV_D0987"]
fields = ['PHA1', 'AMP1', 'PHASE1', 'AMPLITUDE1',
          'PHA2', 'AMP2', 'PHASE2', 'AMPLITUDE2',
          'PHA3', 'AMP3', 'PHASE3', 'AMPLITUDE3',
          'PHA1_CREST', 'PHASE1_CREST', 'AMP1_COEF', 'AMPLITUDE1_COEF',
          'PHA2_CREST', 'PHASE2_CREST', 'AMP2_COEF', 'AMPLITUDE2_COEF',
          'PHA3_CREST', 'PHASE3_CREST', 'AMP3_COEF', 'AMPLITUDE3_COEF',
]

[HCOR]
fields = ['I', 'TM']

[VCOR]
fields = ['I', 'TM']

[SOL]
fields = ['I', 'B']

[BEND]
fields = ['I', 'B']

[EBEND]
fields = ['V', 'VOLT']

[EQUAD]
fields = ['V', 'VOLT']

[QUAD]
fields = ['I', 'B2']

[SEXT]
fields = ['I', 'B3']

# ISRC1
[HVP]
fields = ['V', 'VOLT']
[SEL]
fields = ['V', 'VOLT']
[SB]
fields = ['V', 'VOLT']
[SX]
fields = ['V', 'VOLT']
[SE]
fields = ['V', 'VOLT']
