# Configuration file for Settings Manager >= 9.0
#
TITLE = "Configurations for Settings Manager"

[DATA_SOURCE]
  TYPE = 'DB' # FILE, DB
  DB_ENGINE = 'sqlite'
  URI = '/files/shared/ap/settings_manager/sm.db'

  # TYPE = 'FILE'
  # URI = '/files/shared/ap/settings_manager'  # where reside all snapshot files

[SETTINGS]
  T_WAIT = 0.05  # Settling time between batch settings apply, second
  TOLERANCE = 0.10 # defalut absolute discrepancy tolerance
  PRECISION = 3 # float number precision
  FIELD_INIT_MODE = 'model' # initial settings with model or live data
  INIT_SETTINGS = false     # initialize settings table or not
  SUPPORT_CONFIG_PATH = "/files/shared/ap/settings_manager/.config/" # elements,settings,tolerance.json
  # HIDE_COLUMNS = ['dx01', 'tolerance', 'writable']

[MACH_STATE]
  # CONFIG_PATH = "/files/shared/ap/HLA/.phyapps/phantasy-apps/phantasy_apps/msviz/config/metadata.toml"
  CONFIG_PATH = "/files/shared/ap/settings_manager/metadata.toml"
  ENABLED = true
  DAQ_RATE = 5
  DAQ_NSHOT = 20

[DATA_REFRESH]
  NCORE = 4 # max number of CPU cores to use

[LATTICE]
  DEFAULT_MACHINE = 'FRIB'
  DEFAULT_SEGMENT = 'LINAC'

[ARCHIVER_APPLIANCE]
  [ARCHIVER_APPLIANCE.DATA_CLIENT]
    URL = "http://epicsarchiver1.ftc:17668"

[SNAPSHOT_TEMPLATES]
  [SNAPSHOT_TEMPLATES."LINAC_Artemis"]
    NAME = "LINAC_Artemis"
    DB_ENTRY = "2022-04-20T10:14:52"
    DB_TAGS = ["LINAC", "SCS1"]

  [SNAPSHOT_TEMPLATES."FSEE_Artemis"]
    NAME = "FSEE_Artemis"
    DB_ENTRY = "2022-03-22T13:47:28"
    DB_TAGS = ["FSEE", "SCS1"]

  [SNAPSHOT_TEMPLATES."LINAC_HP-ECR"]
    NAME = "LINAC_HP-ECR"
    DB_ENTRY = "2023-03-20T14:08:35"
    DB_TAGS = ["LINAC", "SCS2"]

  [SNAPSHOT_TEMPLATES."FSEE_HP-ECR"]
    NAME = "FSEE_HP-ECR"
    DB_ENTRY = "2023-03-20T12:02:59"
    DB_TAGS = ["FSEE", "SCS2"]

[EXTERNAL_APPS]
  [EXTERNAL_APPS.APP1]
    NAME = "Viola"
    EXEC = "python3 /files/shared/ap/OnlineViewerApp/viola.py"
    ARGS = "--setting {ename}.json"
    CWD = "/files/shared/ap/OnlineViewerApp/devices"
  [EXTERNAL_APPS.APP2]
    NAME = "Correlation Visualizer"
    EXEC = "correlation_visualizer"
  #   ARGS = ""
  #   CWD = ""

[FILTER_BUTTONS]
[FILTER_BUTTONS.BTN1]
FILEPATH = "/files/shared/ap/settings_manager/filters/01_scaling.flt"

[FILTER_GROUPS]
[FILTER_GROUPS.GRP1]
NAME = "Filters"
DESC = "Choose predefined filters..."
DIRPATH = "/files/shared/ap/settings_manager/filters"

# other configuration data
[DATA]
  # tolerance PVs
  TOL_PVFILE = "/files/shared/ap/HLA/.phyapps/phantasy-apps/phantasy_apps/settings_manager/config/tolpv.json"
  # reference set PVs
  REFST_PVFILE = "/files/shared/ap/HLA/.phyapps/phantasy-apps/phantasy_apps/settings_manager/config/refstpv.json"
  # alarm switch PVs
  ALMACT_PVFILE = "/files/shared/ap/HLA/.phyapps/phantasy-apps/phantasy_apps/settings_manager/config/almactpv.json"
