# Configuration file for Settings Manager >= 9.0
#
TITLE = "Configurations for Settings Manager"

[DATA_SOURCE]
  TYPE = 'DB' # DB (database)
  DB_ENGINE = 'sqlite'
  URI = '~/settings_manager/sm.db'
  # URI = '/home/tong/Dropbox/phantasy-project/phantasy-apps/phantasy_apps/settings_manager/testdata/settings_manager/sm.db'

[SETTINGS]
  T_WAIT = 0.05  # Settling time between batch settings apply, second
  TOLERANCE = 0.10 # defalut absolute discrepancy tolerance
  PRECISION = 3 # float number precision
  FIELD_INIT_MODE = 'model' # initial settings with model or live data
  INIT_SETTINGS = false     # initialize settings table or not
  SUPPORT_CONFIG_PATH = "~/.phantasy-apps/settings-manager" # elements,settings,tolerance.json
  # HIDE_COLUMNS = ['dx01', 'tolerance', 'writable']

[MACH_STATE]
  CONFIG_PATH = "/home/tong/Dropbox/phantasy-project/phantasy-apps/phantasy_apps/msviz/config/metadata_va.toml"
  ENABLED = false
  DAQ_RATE = 5
  DAQ_NSHOT = 20

[DATA_REFRESH]
  NCORE = 4 # max CPU cores to use

[LATTICE]
  DEFAULT_MACHINE = 'FRIB_VA'
  DEFAULT_SEGMENT = 'LS1FS1'

[ARCHIVER_APPLIANCE]
  [ARCHIVER_APPLIANCE.DATA_CLIENT]
    URL = "http://127.0.0.1:17665"

# Apps that could be launched from the context menu of the first column
# of settings view.
# args: ename (element name) machine (machine name), segment (segment name)
[EXTERNAL_APPS]
  [EXTERNAL_APPS.APP1]
    NAME = "Correlation Visualizer"
    EXEC = "correlation_visualizer"
    ARGS = "--config {ename}.json"

# EPICS : do not use
#[EPICS]
#  CA_AUTO_ADDR_LIST = "NO"
#  CA_ADDR_LIST = ["localhost", "controlgw1.nscl.msu.edu:6064", "controlgw2.nscl.msu.edu:6064"]

# other configuration data
[DATA]
  # tolerance PVs
  TOL_PVFILE = "/home/tong/Dropbox/phantasy-project/phantasy-apps/phantasy_apps/settings_manager/config/tolpv.json"
  # reference set PVs
  REFST_PVFILE = "/home/tong/Dropbox/phantasy-project/phantasy-apps/phantasy_apps/settings_manager/config/refstpv.json"
  # alarm switch PVs
  ALMACT_PVFILE = "/home/tong/Dropbox/phantasy-project/phantasy-apps/phantasy_apps/settings_manager/config/almactpv.json"
