# Configuration file for running Settings Manager in FTC.
#
TITLE = "App Configurations for Settings Manager, passing with --config"

[UI]
HEIGHT = 1440
WIDTH = 1920

[DATA_SOURCE]
DB_ENGINE = "sqlite"
TYPE = "database"
URI = "/files/shared/ap/settings_manager/sm_new.db"

[SETTINGS]
FIELD_INIT_MODE = "model" # initial settings with model or live data, if live is enabled, saved set will be overridden
HIDDEN_COLUMNS = [
  "Pos [m]",
  "Tolerance",
  "Writable?",
  "SavedSet-LiveRead\n(x₀-x₁)",
  "RefSet\n(xref)",
  "LiveSet-RefSet\n(x₂-xref)",
  "SavedSet-RefSet\n(x₀-xref)",
  "Tune Alarm\nEnabled?",
  "Read Alarm\nEnabled?",
] 
PRECISION = 3 # float number precision
SKIP_NONE = true # whether skip device settings with none returned
TOLERANCE = 0.10 # defalut absolute discrepancy tolerance
T_WAIT = 50 # Settling time between batch settings apply, milliseconds
# machine specific
SCALABLE_FIELD_NAMES = ["I", "V", "AMP", "AMP1", "AMP2", "AMP3", "I_TC"] 
STRIPPER_POS = 224.90368452 # meter, carbon stripper location
# for those write permission allowed per ACF but intended to be readonly.
READONLY_DEVICE_LIST = [
  'FE_ISRC1:BEAM',
  'FE_ISRC1:DRV_D0686',
  'FE_ISRC1:HVP_D0679',
  'FE_ISRC1:PSEL_D0679',
  'FE_ISRC1:PSX_D0679',
  'FE_ISRC1:PSB_D0679',
  'FE_ISRC1:SOLR_D0682',
  'FE_ISRC1:SOLR_D0685',
  'FE_ISRC1:PSE_D0686',
  'FE_ISRC1:DRV_D0686',
  'FE_ISRC1:PSEL_D0698',
  'FE_ISRC1:HVP_D0698',
  'FE_ISRC2:BEAM',
  'FE_SRC2:PSEL_D0651',
  'FE_SRC2:HVP_D0652',
  'FE_SRC2:PSB_D0659',
  'FE_SRC2:SOLS_D0659',
  'FE_SRC2:S_D0661',
  'FE_SRC2:SOLS_D0662',
  'FE_SRC2:SOLS_D0664',
  'FE_SRC2:PSE_D0665',
  'FE_SRC2:HVP_D0677',
  'FE_SRC2:PSEL_D0678',
  'FE_SRC2:PSX_N0003',
  'FE_SRC2:PSX_N0002',
  'FE_SRC2:PSX_N0001',
  'FE_LEBT:BEAM',
  'FE_LEBT:ATT_D0957-1',
  'FE_LEBT:ATT_D0957-2',
  'FE_LEBT:ATT_D0974-1',
  'FE_LEBT:ATT_D0974-2',
  'FE_LEBT:AP_D0796',
  'FE_LEBT:AP_D0807',
  'FE_RFQ:CAV_D1005',
  'FS1_CSS:STRIP_D2249',
]

# if not defined, use the app distributed one.
# relative path w.r.t. the main app config file.
[FIELD_OF_INTEREST]
FILEPATH = "fields.toml"

[OPI]
SNP_AUTHOR_PV = "PHY:SM_SNP_LAST_AUTHOR"
SNP_ION_PV = "PHY:SM_SNP_LAST_ION"
SNP_NAME_PV = "PHY:SM_SNP_LAST_NAME"
SNP_NOTE_PV = "PHY:SM_SNP_LAST_NOTE"
SNP_PUBLISHER_PV = "PHY:SM_SNP_LAST_PUBLISHER"

[MACH_STATE]
CONFIG_PATH = "/files/shared/ap/settings_manager/metadata.toml"
DAQ_NSHOT = 20
DAQ_RATE = 5
ENABLED = true

[DATA_REFRESH]
NCORE = 4 # max CPU cores to use

[LATTICE]
DEFAULT_MACHINE = "FRIB"
DEFAULT_SEGMENT = "LINAC"

[ARCHIVER_APPLIANCE]
[ARCHIVER_APPLIANCE.DATA_CLIENT]
URL = "http://epicsarchiver1.ftc:17668"

# Apps that could be launched from the context menu of the first column
# of settings view.
# args: ename (element name) machine (machine name), segment (segment name)
[EXTERNAL_APPS]
[EXTERNAL_APPS.APP1]
ARGS = "--setting {ename}.json"
CWD = "/files/shared/ap/OnlineViewerApp/devices"
EXEC = "python3 /files/shared/ap/OnlineViewerApp/viola.py"
NAME = "Viola"
[EXTERNAL_APPS.APP2]
EXEC = "correlation_visualizer"
NAME = "Correlation Visualizer"
#   ARGS = ""
#   CWD = ""

[FILTER_BUTTONS]
[FILTER_BUTTONS.BTN1]
FILEPATH = "/files/shared/ap/settings_manager/filters/01_scaling.flt"

[FILTER_GROUPS]
[FILTER_GROUPS.GRP1]
DESC = "Choose predefined filters..."
DIRPATH = "/files/shared/ap/settings_manager/filters"
NAME = "Filters"

[SNAPSHOT_TAKE]
# predefined tag list to use when take a snapshot.
EXCL_TAG_GROUPS = [["LINAC", "FSEE"], ["SCS1", "SCS2"]]
TAGS = ["GOLDEN", "FSEE", "LINAC", "SCS1", "SCS2", "TEST", "TEMPLATE"]

[BEAM]
# machine bound list
MACHINE_BOUNDS = ["LINAC", "FSEE"]
# ion source list
ISRC_ALIAS = ["ISRC1", "ISRC2"]
ISRC_NAMES = ["Artemis", "HP-ECR"]

[SNAPSHOT_TEMPLATES]

[SNAPSHOT_TEMPLATES."LINAC_Artemis"]
DB_ENTRY = "2023-09-19T14:59:35"
DB_TAGS = ["LINAC", "SCS1"]
NAME = "LINAC_Artemis"

[SNAPSHOT_TEMPLATES."FSEE_Artemis"]
DB_ENTRY = "2023-09-19T14:46:34"
DB_TAGS = ["FSEE", "SCS1"]
NAME = "FSEE_Artemis"

[SNAPSHOT_TEMPLATES."LINAC_HP-ECR"]
DB_ENTRY = "2023-09-19T14:58:01"
DB_TAGS = ["LINAC", "SCS2"]
NAME = "LINAC_HP-ECR"

[SNAPSHOT_TEMPLATES."FSEE_HP-ECR"]
DB_ENTRY = "2023-09-19T14:52:10"
DB_TAGS = ["FSEE", "SCS2"]
NAME = "FSEE_HP-ECR"

# other configuration data
[DATA]
# tolerance PVs
TOL_PVFILE = "/files/shared/ap/HLA/.phyapps/phantasy-apps/phantasy_apps/settings_manager/config/tolpv.json"
# reference set PVs
REFST_PVFILE = "/files/shared/ap/HLA/.phyapps/phantasy-apps/phantasy_apps/settings_manager/config/refstpv.json"
# alarm switch PVs
ALMACT_PVFILE = "/files/shared/ap/HLA/.phyapps/phantasy-apps/phantasy_apps/settings_manager/config/almactpv.json"

[ATTACHMENT]
  # attach after upload?
  ATTACH_AFTER_UPLOAD = true
  # keep all the data files.
  DATA_DIR = "/files/shared/ap/settings_manager/attachments"
  [ATTACHMENT.FILE_TYPE_EXEC]
    SNP = "libreoffice --calc"
    CSV = "libreoffice --calc"
    TXT = "gedit"
