# Configuration file for Settings Manager >= 9.0
#
TITLE = "Configurations for Settings Manager"

[DATA_SOURCE]
  TYPE = 'DB' # FILE, DB
  DB_ENGINE = 'sqlite'
  URI = '/files/shared/ap/settings_manager/sm.db'

  # TYPE = 'FILE'
  # URI = '/files/shared/ap/settings_manager'  # where reside all snapshot files

[SETTINGS]
  T_WAIT = 0.05  # Settling time between batch settings apply, second
  TOLERANCE = 0.10 # defalut absolute discrepancy tolerance
  PRECISION = 3 # float number precision
  FIELD_INIT_MODE = 'model' # initial settings with model or live data
  INIT_SETTINGS = false     # initialize settings table or not
  SUPPORT_CONFIG_PATH = "~/.phantasy-apps/settings-manager" # elements,settings,tolerance.json
  # HIDE_COLUMNS = ['dx01', 'tolerance', 'writable']

[MACH_STATE]
  CONFIG_PATH = "/home/tong/Dropbox/phantasy-project/phantasy-apps/phantasy_apps/msviz/config/metadata_va.toml"
  ENABLED = true

[DATA_REFRESH]
  NCORE = 4 # max CPU cores to use

[LATTICE]
  DEFAULT_MACHINE = 'FRIB'
  DEFAULT_SEGMENT = 'LINAC'
