# Keep PV-of-interest for data retriever when taking snapshot
# The values are the addtional metadata for the machine settings.
#
# Section DAQ: define DAQ rate and shot number.
# Each other section keep a list of general PV names to fetch data via caget
# the section name could be defined w.r.t. the purposes, with a list of PVs
# under key 'names'.
#
[DAQ]
# rate (Hz), shot number
rate = 5
nshot = 20

[traj-x]
names = [
'VA:LS1_CA01:BPM_D1129:X_RD',
'VA:LS1_CA01:BPM_D1144:X_RD',
'VA:LS1_WA01:BPM_D1155:X_RD',
'VA:LS1_CA02:BPM_D1163:X_RD',
'VA:LS1_CA02:BPM_D1177:X_RD',
'VA:LS1_WA02:BPM_D1188:X_RD',
'VA:LS1_CA03:BPM_D1196:X_RD',
'VA:LS1_CA03:BPM_D1211:X_RD',
'VA:LS1_WA03:BPM_D1222:X_RD',
'VA:LS1_CB01:BPM_D1231:X_RD',
'VA:LS1_CB01:BPM_D1251:X_RD',
'VA:LS1_CB01:BPM_D1271:X_RD',
'VA:LS1_WB01:BPM_D1286:X_RD',
'VA:LS1_CB02:BPM_D1295:X_RD',
'VA:LS1_CB02:BPM_D1315:X_RD',
'VA:LS1_CB02:BPM_D1335:X_RD',
'VA:LS1_WB02:BPM_D1350:X_RD',
'VA:LS1_CB03:BPM_D1359:X_RD',
'VA:LS1_CB03:BPM_D1379:X_RD',
'VA:LS1_CB03:BPM_D1399:X_RD',
'VA:LS1_WB03:BPM_D1413:X_RD',
'VA:LS1_CB04:BPM_D1423:X_RD',
'VA:LS1_CB04:BPM_D1442:X_RD',
'VA:LS1_CB04:BPM_D1462:X_RD',
'VA:LS1_WB04:BPM_D1477:X_RD',
'VA:LS1_CB05:BPM_D1486:X_RD',
'VA:LS1_CB05:BPM_D1506:X_RD',
'VA:LS1_CB05:BPM_D1526:X_RD',
'VA:LS1_WB05:BPM_D1541:X_RD',
'VA:LS1_CB06:BPM_D1550:X_RD',
'VA:LS1_CB06:BPM_D1570:X_RD',
'VA:LS1_CB06:BPM_D1590:X_RD',
'VA:LS1_WB06:BPM_D1604:X_RD',
'VA:LS1_CB07:BPM_D1614:X_RD',
'VA:LS1_CB07:BPM_D1634:X_RD',
'VA:LS1_CB07:BPM_D1654:X_RD',
'VA:LS1_WB07:BPM_D1668:X_RD',
'VA:LS1_CB08:BPM_D1677:X_RD',
'VA:LS1_CB08:BPM_D1697:X_RD',
'VA:LS1_CB08:BPM_D1717:X_RD',
'VA:LS1_WB08:BPM_D1732:X_RD',
'VA:LS1_CB09:BPM_D1741:X_RD',
'VA:LS1_CB09:BPM_D1761:X_RD',
'VA:LS1_CB09:BPM_D1781:X_RD',
'VA:LS1_WB09:BPM_D1796:X_RD',
'VA:LS1_CB10:BPM_D1805:X_RD',
'VA:LS1_CB10:BPM_D1825:X_RD',
'VA:LS1_CB10:BPM_D1845:X_RD',
'VA:LS1_WB10:BPM_D1859:X_RD',
'VA:LS1_CB11:BPM_D1869:X_RD',
'VA:LS1_CB11:BPM_D1889:X_RD',
'VA:LS1_CB11:BPM_D1909:X_RD',
'VA:LS1_WB11:BPM_D1923:X_RD',
'VA:LS1_BTS:BPM_D1967:X_RD',
'VA:LS1_BTS:BPM_D1980:X_RD',
'VA:LS1_BTS:BPM_D2027:X_RD',
'VA:LS1_BTS:BPM_D2054:X_RD',
'VA:LS1_BTS:BPM_D2116:X_RD',
'VA:LS1_BTS:BPM_D2130:X_RD',
'VA:FS1_CSS:BPM_D2212:X_RD',
'VA:FS1_CSS:BPM_D2223:X_RD',
'VA:FS1_CSS:BPM_D2248:X_RD',
'VA:FS1_CSS:BPM_D2278:X_RD',
'VA:FS1_CSS:BPM_D2313:X_RD',
'VA:FS1_CSS:BPM_D2369:X_RD',
'VA:FS1_CSS:BPM_D2383:X_RD',
'VA:FS1_BBS:BPM_D2421:X_RD',
'VA:FS1_BBS:BPM_D2466:X_RD',
'VA:FS1_BMS:BPM_D2502:X_RD',
'VA:FS1_BMS:BPM_D2537:X_RD',
'VA:FS1_BMS:BPM_D2587:X_RD',
'VA:FS1_BMS:BPM_D2600:X_RD',
'VA:FS1_BMS:BPM_D2665:X_RD',
'VA:FS1_BMS:BPM_D2690:X_RD',
'VA:FS1_BMS:BPM_D2702:X_RD',
]

[traj-y]
names = [
'VA:LS1_CA01:BPM_D1129:Y_RD',
'VA:LS1_CA01:BPM_D1144:Y_RD',
'VA:LS1_WA01:BPM_D1155:Y_RD',
'VA:LS1_CA02:BPM_D1163:Y_RD',
'VA:LS1_CA02:BPM_D1177:Y_RD',
'VA:LS1_WA02:BPM_D1188:Y_RD',
'VA:LS1_CA03:BPM_D1196:Y_RD',
'VA:LS1_CA03:BPM_D1211:Y_RD',
'VA:LS1_WA03:BPM_D1222:Y_RD',
'VA:LS1_CB01:BPM_D1231:Y_RD',
'VA:LS1_CB01:BPM_D1251:Y_RD',
'VA:LS1_CB01:BPM_D1271:Y_RD',
'VA:LS1_WB01:BPM_D1286:Y_RD',
'VA:LS1_CB02:BPM_D1295:Y_RD',
'VA:LS1_CB02:BPM_D1315:Y_RD',
'VA:LS1_CB02:BPM_D1335:Y_RD',
'VA:LS1_WB02:BPM_D1350:Y_RD',
'VA:LS1_CB03:BPM_D1359:Y_RD',
'VA:LS1_CB03:BPM_D1379:Y_RD',
'VA:LS1_CB03:BPM_D1399:Y_RD',
'VA:LS1_WB03:BPM_D1413:Y_RD',
'VA:LS1_CB04:BPM_D1423:Y_RD',
'VA:LS1_CB04:BPM_D1442:Y_RD',
'VA:LS1_CB04:BPM_D1462:Y_RD',
'VA:LS1_WB04:BPM_D1477:Y_RD',
'VA:LS1_CB05:BPM_D1486:Y_RD',
'VA:LS1_CB05:BPM_D1506:Y_RD',
'VA:LS1_CB05:BPM_D1526:Y_RD',
'VA:LS1_WB05:BPM_D1541:Y_RD',
'VA:LS1_CB06:BPM_D1550:Y_RD',
'VA:LS1_CB06:BPM_D1570:Y_RD',
'VA:LS1_CB06:BPM_D1590:Y_RD',
'VA:LS1_WB06:BPM_D1604:Y_RD',
'VA:LS1_CB07:BPM_D1614:Y_RD',
'VA:LS1_CB07:BPM_D1634:Y_RD',
'VA:LS1_CB07:BPM_D1654:Y_RD',
'VA:LS1_WB07:BPM_D1668:Y_RD',
'VA:LS1_CB08:BPM_D1677:Y_RD',
'VA:LS1_CB08:BPM_D1697:Y_RD',
'VA:LS1_CB08:BPM_D1717:Y_RD',
'VA:LS1_WB08:BPM_D1732:Y_RD',
'VA:LS1_CB09:BPM_D1741:Y_RD',
'VA:LS1_CB09:BPM_D1761:Y_RD',
'VA:LS1_CB09:BPM_D1781:Y_RD',
'VA:LS1_WB09:BPM_D1796:Y_RD',
'VA:LS1_CB10:BPM_D1805:Y_RD',
'VA:LS1_CB10:BPM_D1825:Y_RD',
'VA:LS1_CB10:BPM_D1845:Y_RD',
'VA:LS1_WB10:BPM_D1859:Y_RD',
'VA:LS1_CB11:BPM_D1869:Y_RD',
'VA:LS1_CB11:BPM_D1889:Y_RD',
'VA:LS1_CB11:BPM_D1909:Y_RD',
'VA:LS1_WB11:BPM_D1923:Y_RD',
'VA:LS1_BTS:BPM_D1967:Y_RD',
'VA:LS1_BTS:BPM_D1980:Y_RD',
'VA:LS1_BTS:BPM_D2027:Y_RD',
'VA:LS1_BTS:BPM_D2054:Y_RD',
'VA:LS1_BTS:BPM_D2116:Y_RD',
'VA:LS1_BTS:BPM_D2130:Y_RD',
'VA:FS1_CSS:BPM_D2212:Y_RD',
'VA:FS1_CSS:BPM_D2223:Y_RD',
'VA:FS1_CSS:BPM_D2248:Y_RD',
'VA:FS1_CSS:BPM_D2278:Y_RD',
'VA:FS1_CSS:BPM_D2313:Y_RD',
'VA:FS1_CSS:BPM_D2369:Y_RD',
'VA:FS1_CSS:BPM_D2383:Y_RD',
'VA:FS1_BBS:BPM_D2421:Y_RD',
'VA:FS1_BBS:BPM_D2466:Y_RD',
'VA:FS1_BMS:BPM_D2502:Y_RD',
'VA:FS1_BMS:BPM_D2537:Y_RD',
'VA:FS1_BMS:BPM_D2587:Y_RD',
'VA:FS1_BMS:BPM_D2600:Y_RD',
'VA:FS1_BMS:BPM_D2665:Y_RD',
'VA:FS1_BMS:BPM_D2690:Y_RD',
'VA:FS1_BMS:BPM_D2702:Y_RD',
]

[phase]
names = [
'VA:LS1_CA01:BPM_D1129:PHA_RD',
'VA:LS1_CA01:BPM_D1144:PHA_RD',
'VA:LS1_WA01:BPM_D1155:PHA_RD',
'VA:LS1_CA02:BPM_D1163:PHA_RD',
'VA:LS1_CA02:BPM_D1177:PHA_RD',
'VA:LS1_WA02:BPM_D1188:PHA_RD',
'VA:LS1_CA03:BPM_D1196:PHA_RD',
'VA:LS1_CA03:BPM_D1211:PHA_RD',
'VA:LS1_WA03:BPM_D1222:PHA_RD',
'VA:LS1_CB01:BPM_D1231:PHA_RD',
'VA:LS1_CB01:BPM_D1251:PHA_RD',
'VA:LS1_CB01:BPM_D1271:PHA_RD',
'VA:LS1_WB01:BPM_D1286:PHA_RD',
'VA:LS1_CB02:BPM_D1295:PHA_RD',
'VA:LS1_CB02:BPM_D1315:PHA_RD',
'VA:LS1_CB02:BPM_D1335:PHA_RD',
'VA:LS1_WB02:BPM_D1350:PHA_RD',
'VA:LS1_CB03:BPM_D1359:PHA_RD',
'VA:LS1_CB03:BPM_D1379:PHA_RD',
'VA:LS1_CB03:BPM_D1399:PHA_RD',
'VA:LS1_WB03:BPM_D1413:PHA_RD',
'VA:LS1_CB04:BPM_D1423:PHA_RD',
'VA:LS1_CB04:BPM_D1442:PHA_RD',
'VA:LS1_CB04:BPM_D1462:PHA_RD',
'VA:LS1_WB04:BPM_D1477:PHA_RD',
'VA:LS1_CB05:BPM_D1486:PHA_RD',
'VA:LS1_CB05:BPM_D1506:PHA_RD',
'VA:LS1_CB05:BPM_D1526:PHA_RD',
'VA:LS1_WB05:BPM_D1541:PHA_RD',
'VA:LS1_CB06:BPM_D1550:PHA_RD',
'VA:LS1_CB06:BPM_D1570:PHA_RD',
'VA:LS1_CB06:BPM_D1590:PHA_RD',
'VA:LS1_WB06:BPM_D1604:PHA_RD',
'VA:LS1_CB07:BPM_D1614:PHA_RD',
'VA:LS1_CB07:BPM_D1634:PHA_RD',
'VA:LS1_CB07:BPM_D1654:PHA_RD',
'VA:LS1_WB07:BPM_D1668:PHA_RD',
'VA:LS1_CB08:BPM_D1677:PHA_RD',
'VA:LS1_CB08:BPM_D1697:PHA_RD',
'VA:LS1_CB08:BPM_D1717:PHA_RD',
'VA:LS1_WB08:BPM_D1732:PHA_RD',
'VA:LS1_CB09:BPM_D1741:PHA_RD',
'VA:LS1_CB09:BPM_D1761:PHA_RD',
'VA:LS1_CB09:BPM_D1781:PHA_RD',
'VA:LS1_WB09:BPM_D1796:PHA_RD',
'VA:LS1_CB10:BPM_D1805:PHA_RD',
'VA:LS1_CB10:BPM_D1825:PHA_RD',
'VA:LS1_CB10:BPM_D1845:PHA_RD',
'VA:LS1_WB10:BPM_D1859:PHA_RD',
'VA:LS1_CB11:BPM_D1869:PHA_RD',
'VA:LS1_CB11:BPM_D1889:PHA_RD',
'VA:LS1_CB11:BPM_D1909:PHA_RD',
'VA:LS1_WB11:BPM_D1923:PHA_RD',
'VA:LS1_BTS:BPM_D1967:PHA_RD',
'VA:LS1_BTS:BPM_D1980:PHA_RD',
'VA:LS1_BTS:BPM_D2027:PHA_RD',
'VA:LS1_BTS:BPM_D2054:PHA_RD',
'VA:LS1_BTS:BPM_D2116:PHA_RD',
'VA:LS1_BTS:BPM_D2130:PHA_RD',
'VA:FS1_CSS:BPM_D2212:PHA_RD',
'VA:FS1_CSS:BPM_D2223:PHA_RD',
'VA:FS1_CSS:BPM_D2248:PHA_RD',
'VA:FS1_CSS:BPM_D2278:PHA_RD',
'VA:FS1_CSS:BPM_D2313:PHA_RD',
'VA:FS1_CSS:BPM_D2369:PHA_RD',
'VA:FS1_CSS:BPM_D2383:PHA_RD',
'VA:FS1_BBS:BPM_D2421:PHA_RD',
'VA:FS1_BBS:BPM_D2466:PHA_RD',
'VA:FS1_BMS:BPM_D2502:PHA_RD',
'VA:FS1_BMS:BPM_D2537:PHA_RD',
'VA:FS1_BMS:BPM_D2587:PHA_RD',
'VA:FS1_BMS:BPM_D2600:PHA_RD',
'VA:FS1_BMS:BPM_D2665:PHA_RD',
'VA:FS1_BMS:BPM_D2690:PHA_RD',
'VA:FS1_BMS:BPM_D2702:PHA_RD',
]

[energy]
names = [
'VA:LS1_CA01:BPM_D1129:ENG_RD',
'VA:LS1_CA01:BPM_D1144:ENG_RD',
'VA:LS1_WA01:BPM_D1155:ENG_RD',
'VA:LS1_CA02:BPM_D1163:ENG_RD',
'VA:LS1_CA02:BPM_D1177:ENG_RD',
'VA:LS1_WA02:BPM_D1188:ENG_RD',
'VA:LS1_CA03:BPM_D1196:ENG_RD',
'VA:LS1_CA03:BPM_D1211:ENG_RD',
'VA:LS1_WA03:BPM_D1222:ENG_RD',
'VA:LS1_CB01:BPM_D1231:ENG_RD',
'VA:LS1_CB01:BPM_D1251:ENG_RD',
'VA:LS1_CB01:BPM_D1271:ENG_RD',
'VA:LS1_WB01:BPM_D1286:ENG_RD',
'VA:LS1_CB02:BPM_D1295:ENG_RD',
'VA:LS1_CB02:BPM_D1315:ENG_RD',
'VA:LS1_CB02:BPM_D1335:ENG_RD',
'VA:LS1_WB02:BPM_D1350:ENG_RD',
'VA:LS1_CB03:BPM_D1359:ENG_RD',
'VA:LS1_CB03:BPM_D1379:ENG_RD',
'VA:LS1_CB03:BPM_D1399:ENG_RD',
'VA:LS1_WB03:BPM_D1413:ENG_RD',
'VA:LS1_CB04:BPM_D1423:ENG_RD',
'VA:LS1_CB04:BPM_D1442:ENG_RD',
'VA:LS1_CB04:BPM_D1462:ENG_RD',
'VA:LS1_WB04:BPM_D1477:ENG_RD',
'VA:LS1_CB05:BPM_D1486:ENG_RD',
'VA:LS1_CB05:BPM_D1506:ENG_RD',
'VA:LS1_CB05:BPM_D1526:ENG_RD',
'VA:LS1_WB05:BPM_D1541:ENG_RD',
'VA:LS1_CB06:BPM_D1550:ENG_RD',
'VA:LS1_CB06:BPM_D1570:ENG_RD',
'VA:LS1_CB06:BPM_D1590:ENG_RD',
'VA:LS1_WB06:BPM_D1604:ENG_RD',
'VA:LS1_CB07:BPM_D1614:ENG_RD',
'VA:LS1_CB07:BPM_D1634:ENG_RD',
'VA:LS1_CB07:BPM_D1654:ENG_RD',
'VA:LS1_WB07:BPM_D1668:ENG_RD',
'VA:LS1_CB08:BPM_D1677:ENG_RD',
'VA:LS1_CB08:BPM_D1697:ENG_RD',
'VA:LS1_CB08:BPM_D1717:ENG_RD',
'VA:LS1_WB08:BPM_D1732:ENG_RD',
'VA:LS1_CB09:BPM_D1741:ENG_RD',
'VA:LS1_CB09:BPM_D1761:ENG_RD',
'VA:LS1_CB09:BPM_D1781:ENG_RD',
'VA:LS1_WB09:BPM_D1796:ENG_RD',
'VA:LS1_CB10:BPM_D1805:ENG_RD',
'VA:LS1_CB10:BPM_D1825:ENG_RD',
'VA:LS1_CB10:BPM_D1845:ENG_RD',
'VA:LS1_WB10:BPM_D1859:ENG_RD',
'VA:LS1_CB11:BPM_D1869:ENG_RD',
'VA:LS1_CB11:BPM_D1889:ENG_RD',
'VA:LS1_CB11:BPM_D1909:ENG_RD',
'VA:LS1_WB11:BPM_D1923:ENG_RD',
'VA:LS1_BTS:BPM_D1967:ENG_RD',
'VA:LS1_BTS:BPM_D1980:ENG_RD',
'VA:LS1_BTS:BPM_D2027:ENG_RD',
'VA:LS1_BTS:BPM_D2054:ENG_RD',
'VA:LS1_BTS:BPM_D2116:ENG_RD',
'VA:LS1_BTS:BPM_D2130:ENG_RD',
'VA:FS1_CSS:BPM_D2212:ENG_RD',
'VA:FS1_CSS:BPM_D2223:ENG_RD',
'VA:FS1_CSS:BPM_D2248:ENG_RD',
'VA:FS1_CSS:BPM_D2278:ENG_RD',
'VA:FS1_CSS:BPM_D2313:ENG_RD',
'VA:FS1_CSS:BPM_D2369:ENG_RD',
'VA:FS1_CSS:BPM_D2383:ENG_RD',
'VA:FS1_BBS:BPM_D2421:ENG_RD',
'VA:FS1_BBS:BPM_D2466:ENG_RD',
'VA:FS1_BMS:BPM_D2502:ENG_RD',
'VA:FS1_BMS:BPM_D2537:ENG_RD',
'VA:FS1_BMS:BPM_D2587:ENG_RD',
'VA:FS1_BMS:BPM_D2600:ENG_RD',
'VA:FS1_BMS:BPM_D2665:ENG_RD',
'VA:FS1_BMS:BPM_D2690:ENG_RD',
'VA:FS1_BMS:BPM_D2702:ENG_RD',
]
