# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_2dscan.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vsplitter = QtWidgets.QSplitter(self.centralwidget)
        self.vsplitter.setOrientation(QtCore.Qt.Vertical)
        self.vsplitter.setObjectName("vsplitter")
        self.outer_loop_gbox = QtWidgets.QGroupBox(self.vsplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(
            self.outer_loop_gbox.sizePolicy().hasHeightForWidth())
        self.outer_loop_gbox.setSizePolicy(sizePolicy)
        self.outer_loop_gbox.setObjectName("outer_loop_gbox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.outer_loop_gbox)
        self.horizontalLayout_2.setContentsMargins(4, 10, 4, 4)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hsplitter = QtWidgets.QSplitter(self.outer_loop_gbox)
        self.hsplitter.setOrientation(QtCore.Qt.Horizontal)
        self.hsplitter.setHandleWidth(20)
        self.hsplitter.setObjectName("hsplitter")
        self.layoutWidget = QtWidgets.QWidget(self.hsplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_conf = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_conf.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_conf.setSpacing(4)
        self.gridLayout_conf.setObjectName("gridLayout_conf")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout_conf.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_conf.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_conf.addWidget(self.label_16, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.alter_elem_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.alter_elem_lineEdit.setText("")
        self.alter_elem_lineEdit.setObjectName("alter_elem_lineEdit")
        self.horizontalLayout_11.addWidget(self.alter_elem_lineEdit)
        self.select_alter_elem_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.select_alter_elem_btn.setObjectName("select_alter_elem_btn")
        self.horizontalLayout_11.addWidget(self.select_alter_elem_btn)
        self.gridLayout_conf.addLayout(self.horizontalLayout_11, 0, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lower_limit_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lower_limit_lineEdit.setObjectName("lower_limit_lineEdit")
        self.horizontalLayout_10.addWidget(self.lower_limit_lineEdit)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.upper_limit_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.upper_limit_lineEdit.setObjectName("upper_limit_lineEdit")
        self.horizontalLayout_10.addWidget(self.upper_limit_lineEdit)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.enable_arbitary_array_chkbox = QtWidgets.QCheckBox(
            self.layoutWidget)
        self.enable_arbitary_array_chkbox.setText("")
        self.enable_arbitary_array_chkbox.setObjectName(
            "enable_arbitary_array_chkbox")
        self.horizontalLayout_7.addWidget(self.enable_arbitary_array_chkbox)
        self.alter_array_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.alter_array_btn.setObjectName("alter_array_btn")
        self.horizontalLayout_7.addWidget(self.alter_array_btn)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        self.gridLayout_conf.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_conf.addWidget(self.label_5, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.niter_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.niter_label.sizePolicy().hasHeightForWidth())
        self.niter_label.setSizePolicy(sizePolicy)
        self.niter_label.setObjectName("niter_label")
        self.horizontalLayout_8.addWidget(self.niter_label)
        self.niter_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.niter_spinBox.sizePolicy().hasHeightForWidth())
        self.niter_spinBox.setSizePolicy(sizePolicy)
        self.niter_spinBox.setMinimum(1)
        self.niter_spinBox.setMaximum(9999)
        self.niter_spinBox.setProperty("value", 10)
        self.niter_spinBox.setObjectName("niter_spinBox")
        self.horizontalLayout_8.addWidget(self.niter_spinBox)
        self.gridLayout_conf.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.waitsec_dSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.waitsec_dSpinBox.sizePolicy().hasHeightForWidth())
        self.waitsec_dSpinBox.setSizePolicy(sizePolicy)
        self.waitsec_dSpinBox.setSingleStep(0.5)
        self.waitsec_dSpinBox.setProperty("value", 10.0)
        self.waitsec_dSpinBox.setObjectName("waitsec_dSpinBox")
        self.horizontalLayout_9.addWidget(self.waitsec_dSpinBox)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.t_wait_extra_dSpinBox = QtWidgets.QDoubleSpinBox(
            self.layoutWidget)
        self.t_wait_extra_dSpinBox.setObjectName("t_wait_extra_dSpinBox")
        self.horizontalLayout_9.addWidget(self.t_wait_extra_dSpinBox)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.tol_dSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.tol_dSpinBox.setDecimals(4)
        self.tol_dSpinBox.setMaximum(20.0)
        self.tol_dSpinBox.setSingleStep(0.05)
        self.tol_dSpinBox.setProperty("value", 0.01)
        self.tol_dSpinBox.setObjectName("tol_dSpinBox")
        self.horizontalLayout_9.addWidget(self.tol_dSpinBox)
        self.gridLayout_conf.addLayout(self.horizontalLayout_9, 3, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.hsplitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_ctrl = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_ctrl.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_ctrl.setSpacing(4)
        self.gridLayout_ctrl.setObjectName("gridLayout_ctrl")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(4)
        self.formLayout.setObjectName("formLayout")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole,
                                  self.label_22)
        self.stop_btn = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.stop_btn.sizePolicy().hasHeightForWidth())
        self.stop_btn.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/stop.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.stop_btn.setIcon(icon)
        self.stop_btn.setObjectName("stop_btn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole,
                                  self.stop_btn)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole,
                                  self.label_21)
        self.start_btn = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/start.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.start_btn.setIcon(icon1)
        self.start_btn.setObjectName("start_btn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole,
                                  self.start_btn)
        self.gridLayout_ctrl.addLayout(self.formLayout, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout_ctrl.addWidget(self.label, 1, 0, 1, 1)
        self.alter_elem_val_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.alter_elem_val_lineEdit.setObjectName("alter_elem_val_lineEdit")
        self.gridLayout_ctrl.addWidget(self.alter_elem_val_lineEdit, 1, 1, 1,
                                       1)
        self.moi_cbb = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.moi_cbb.sizePolicy().hasHeightForWidth())
        self.moi_cbb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.moi_cbb.setFont(font)
        self.moi_cbb.setObjectName("moi_cbb")
        self.gridLayout_ctrl.addWidget(self.moi_cbb, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_ctrl.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.hsplitter)
        self.dataviz_gbox = QtWidgets.QGroupBox(self.vsplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(
            self.dataviz_gbox.sizePolicy().hasHeightForWidth())
        self.dataviz_gbox.setSizePolicy(sizePolicy)
        self.dataviz_gbox.setObjectName("dataviz_gbox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dataviz_gbox)
        self.horizontalLayout_5.setContentsMargins(4, 10, 4, 4)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.splitter = QtWidgets.QSplitter(self.dataviz_gbox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.avg_mplimagewidget = MatplotlibImageWidget(self.tab1)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.avg_mplimagewidget.setFigureXYlabelFont(font)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.avg_mplimagewidget.setFigureTitleFont(font)
        self.avg_mplimagewidget.setProperty("figureDPI", 120.0)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.avg_mplimagewidget.setFigureXYticksFont(font)
        self.avg_mplimagewidget.setProperty("figureToolbarToggle", False)
        self.avg_mplimagewidget.setAutoColorLimit(True)
        self.avg_mplimagewidget.setObjectName("avg_mplimagewidget")
        self.horizontalLayout_4.addWidget(self.avg_mplimagewidget)
        self.tabWidget_3.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.std_mplimagewidget = MatplotlibImageWidget(self.tab2)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.std_mplimagewidget.setFigureXYlabelFont(font)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.std_mplimagewidget.setFigureTitleFont(font)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.std_mplimagewidget.setFigureXYticksFont(font)
        self.std_mplimagewidget.setProperty("figureToolbarToggle", False)
        self.std_mplimagewidget.setAutoColorLimit(True)
        self.std_mplimagewidget.setObjectName("std_mplimagewidget")
        self.horizontalLayout_3.addWidget(self.std_mplimagewidget)
        self.tabWidget_3.addTab(self.tab2, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.curve_mplebwidget = MatplotlibErrorbarWidget(self.tab)
        self.curve_mplebwidget.setFigureAutoScale(True)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.curve_mplebwidget.setFigureXYlabelFont(font)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.curve_mplebwidget.setFigureTitleFont(font)
        self.curve_mplebwidget.setProperty("figureDPI", 120.0)
        self.curve_mplebwidget.setProperty("figureLegendToggle", True)
        font = QtGui.QFont()
        font.setFamily("sans-serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.curve_mplebwidget.setFigureXYticksFont(font)
        self.curve_mplebwidget.setProperty("figureToolbarToggle", False)
        self.curve_mplebwidget.setObjectName("curve_mplebwidget")
        self.horizontalLayout_6.addWidget(self.curve_mplebwidget)
        self.tabWidget_2.addTab(self.tab, "")
        self.horizontalLayout_5.addWidget(self.splitter)
        self.analysis_gbox = QtWidgets.QGroupBox(self.vsplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.analysis_gbox.sizePolicy().hasHeightForWidth())
        self.analysis_gbox.setSizePolicy(sizePolicy)
        self.analysis_gbox.setObjectName("analysis_gbox")
        self.gridLayout = QtWidgets.QGridLayout(self.analysis_gbox)
        self.gridLayout.setContentsMargins(4, 10, 4, 4)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.analysis_gbox)
        self.label_10.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.analysis_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.data_hbox = QtWidgets.QHBoxLayout(self.widget)
        self.data_hbox.setContentsMargins(0, 0, 0, 0)
        self.data_hbox.setSpacing(4)
        self.data_hbox.setObjectName("data_hbox")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/icons/rarrow.png"))
        self.label_13.setObjectName("label_13")
        self.data_hbox.addWidget(self.label_13)
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.data_hbox.addWidget(self.label_4)
        self.xdata_cbb = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.xdata_cbb.sizePolicy().hasHeightForWidth())
        self.xdata_cbb.setSizePolicy(sizePolicy)
        self.xdata_cbb.setObjectName("xdata_cbb")
        self.data_hbox.addWidget(self.xdata_cbb)
        self.label_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.data_hbox.addWidget(self.label_6)
        self.ydata_cbb = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ydata_cbb.sizePolicy().hasHeightForWidth())
        self.ydata_cbb.setSizePolicy(sizePolicy)
        self.ydata_cbb.setObjectName("ydata_cbb")
        self.data_hbox.addWidget(self.ydata_cbb)
        self.label_7 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.data_hbox.addWidget(self.label_7)
        self.zdata_cbb = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.zdata_cbb.sizePolicy().hasHeightForWidth())
        self.zdata_cbb.setSizePolicy(sizePolicy)
        self.zdata_cbb.setObjectName("zdata_cbb")
        self.data_hbox.addWidget(self.zdata_cbb)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.analysis_gbox)
        self.label_11.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.analysis_gbox)
        self.widget1.setObjectName("widget1")
        self.plot_hbox = QtWidgets.QHBoxLayout(self.widget1)
        self.plot_hbox.setContentsMargins(0, 0, 0, 0)
        self.plot_hbox.setSpacing(4)
        self.plot_hbox.setObjectName("plot_hbox")
        self.label_14 = QtWidgets.QLabel(self.widget1)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/icons/rarrow.png"))
        self.label_14.setObjectName("label_14")
        self.plot_hbox.addWidget(self.label_14)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.plot_hbox.addWidget(self.label_8)
        self.interp_method_cbb = QtWidgets.QComboBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.interp_method_cbb.sizePolicy().hasHeightForWidth())
        self.interp_method_cbb.setSizePolicy(sizePolicy)
        self.interp_method_cbb.setObjectName("interp_method_cbb")
        self.interp_method_cbb.addItem("")
        self.interp_method_cbb.addItem("")
        self.interp_method_cbb.addItem("")
        self.plot_hbox.addWidget(self.interp_method_cbb)
        self.label_9 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignRight
                                  | QtCore.Qt.AlignTrailing
                                  | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.plot_hbox.addWidget(self.label_9)
        self.interp_nx_sbox = QtWidgets.QSpinBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.interp_nx_sbox.sizePolicy().hasHeightForWidth())
        self.interp_nx_sbox.setSizePolicy(sizePolicy)
        self.interp_nx_sbox.setMinimum(1)
        self.interp_nx_sbox.setMaximum(9999)
        self.interp_nx_sbox.setProperty("value", 1)
        self.interp_nx_sbox.setObjectName("interp_nx_sbox")
        self.plot_hbox.addWidget(self.interp_nx_sbox)
        self.label_12 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignRight
                                   | QtCore.Qt.AlignTrailing
                                   | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.plot_hbox.addWidget(self.label_12)
        self.interp_ny_sbox = QtWidgets.QSpinBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.interp_ny_sbox.sizePolicy().hasHeightForWidth())
        self.interp_ny_sbox.setSizePolicy(sizePolicy)
        self.interp_ny_sbox.setMinimum(1)
        self.interp_ny_sbox.setMaximum(9999)
        self.interp_ny_sbox.setProperty("value", 1)
        self.interp_ny_sbox.setObjectName("interp_ny_sbox")
        self.plot_hbox.addWidget(self.interp_ny_sbox)
        self.gridLayout.addWidget(self.widget1, 1, 1, 1, 1)
        self.plot_btn = QtWidgets.QPushButton(self.analysis_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.plot_btn.sizePolicy().hasHeightForWidth())
        self.plot_btn.setSizePolicy(sizePolicy)
        self.plot_btn.setObjectName("plot_btn")
        self.gridLayout.addWidget(self.plot_btn, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.vsplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 30))
        self.menubar.setObjectName("menubar")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Scan = QtWidgets.QMenu(self.menubar)
        self.menu_Scan.setObjectName("menu_Scan")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.actionContents = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/help.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.actionContents.setIcon(icon2)
        self.actionContents.setObjectName("actionContents")
        self.actionSaveTask = QtWidgets.QAction(MainWindow)
        self.actionSaveTask.setObjectName("actionSaveTask")
        self.actionLoadTask = QtWidgets.QAction(MainWindow)
        self.actionLoadTask.setObjectName("actionLoadTask")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/save_figure.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionE_xit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.actionE_xit.setIcon(icon4)
        self.actionE_xit.setObjectName("actionE_xit")
        self.menu_Help.addAction(self.actionContents)
        self.menu_Scan.addAction(self.actionSaveTask)
        self.menu_Scan.addAction(self.actionLoadTask)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionE_xit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Scan.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.actionSaveTask.triggered.connect(MainWindow.on_save_task)
        self.actionLoadTask.triggered.connect(MainWindow.on_load_task)
        self.actionSave.triggered.connect(MainWindow.on_save_data)
        self.actionE_xit.triggered.connect(MainWindow.close)
        self.plot_btn.clicked.connect(MainWindow.on_plot_data)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.enable_arbitary_array_chkbox,
                               self.alter_array_btn)
        MainWindow.setTabOrder(self.alter_array_btn, self.tabWidget_3)
        MainWindow.setTabOrder(self.tabWidget_3, self.tabWidget_2)
        MainWindow.setTabOrder(self.tabWidget_2, self.alter_elem_val_lineEdit)
        MainWindow.setTabOrder(self.alter_elem_val_lineEdit, self.moi_cbb)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.outer_loop_gbox.setTitle(
            _translate("MainWindow", "Higher Dimension Configuration"))
        self.label_20.setText(_translate("MainWindow", "Ensure Set"))
        self.label_15.setText(_translate("MainWindow", "Alter Element"))
        self.label_16.setText(_translate("MainWindow", "Alter Range"))
        self.alter_elem_lineEdit.setPlaceholderText(
            _translate(
                "MainWindow",
                "Click \'Select\' to set element as another higher dimension"))
        self.select_alter_elem_btn.setText(_translate("MainWindow", "Select"))
        self.lower_limit_lineEdit.setToolTip(
            _translate("MainWindow", "Start value of the scan range."))
        self.label_17.setText(_translate("MainWindow", "To"))
        self.upper_limit_lineEdit.setToolTip(
            _translate("MainWindow", "Stop value of the scan range."))
        self.enable_arbitary_array_chkbox.setToolTip(
            _translate("MainWindow",
                       "Check to enable altering with arbitary array."))
        self.alter_array_btn.setToolTip(
            _translate("MainWindow", "Set scan range by array."))
        self.alter_array_btn.setText(_translate("MainWindow", "Array"))
        self.label_5.setText(_translate("MainWindow", "Scan Config"))
        self.niter_label.setText(_translate("MainWindow", "Total Steps"))
        self.niter_spinBox.setToolTip(
            _translate("MainWindow", "Total number of points to scan."))
        self.label_3.setText(_translate("MainWindow",
                                        "Alter Timeout [second]"))
        self.waitsec_dSpinBox.setToolTip(
            _translate(
                "MainWindow",
                "Maximum wait time in second for setting the alter element."))
        self.label_19.setText(
            _translate("MainWindow", "Additional Wait Time [sec]"))
        self.t_wait_extra_dSpinBox.setToolTip(
            _translate(
                "MainWindow",
                "Additional wait time in second after setting the alter element."
            ))
        self.label_18.setText(
            _translate(
                "MainWindow",
                "<html><head/><body><p>Tolerance of <span style=\" font-style:italic;\">Δ</span><span style=\" font-style:italic; vertical-align:sub;\">rd, set</span></p></body></html>"
            ))
        self.tol_dSpinBox.setToolTip(
            _translate(
                "MainWindow",
                "Discrepancy tolerance between set and get of alter element."))
        self.label_22.setText(
            _translate("MainWindow", "Start Running 2D Scan Task"))
        self.stop_btn.setToolTip(_translate("MainWindow", "Stop task."))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.label_21.setText(
            _translate("MainWindow", "Stop Running 2D Scan Task"))
        self.start_btn.setToolTip(_translate("MainWindow", "Start task."))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Current Settings"))
        self.alter_elem_val_lineEdit.setToolTip(
            _translate("MainWindow", "Current setting of alter element."))
        self.moi_cbb.setToolTip(
            _translate(
                "MainWindow",
                "Interested monitor to show in the data visualization area."))
        self.label_2.setText(_translate("MainWindow", "Monitor of Interest"))
        self.dataviz_gbox.setTitle(
            _translate("MainWindow", "Data Visualization"))
        self.avg_mplimagewidget.setFigureAspectRatio(
            _translate("MainWindow", "auto"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab1),
                                    _translate("MainWindow", "Average"))
        self.std_mplimagewidget.setFigureAspectRatio(
            _translate("MainWindow", "auto"))
        self.tabWidget_3.setTabText(
            self.tabWidget_3.indexOf(self.tab2),
            _translate("MainWindow", "Standard Deviation"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab),
                                    _translate("MainWindow", "Curve"))
        self.analysis_gbox.setTitle(_translate("MainWindow",
                                               "Post-processing"))
        self.label_10.setText(_translate("MainWindow", "Data"))
        self.label_4.setText(_translate("MainWindow", "X-Data"))
        self.label_6.setText(_translate("MainWindow", "Y-Data"))
        self.label_7.setText(_translate("MainWindow", "Z-Data"))
        self.label_11.setText(_translate("MainWindow", "Interpolation"))
        self.label_8.setText(_translate("MainWindow", "Method"))
        self.interp_method_cbb.setItemText(0,
                                           _translate("MainWindow", "Nearest"))
        self.interp_method_cbb.setItemText(1,
                                           _translate("MainWindow", "Linear"))
        self.interp_method_cbb.setItemText(2,
                                           _translate("MainWindow", "Cubic"))
        self.label_9.setText(_translate("MainWindow", "# of Points (X)"))
        self.label_12.setText(_translate("MainWindow", "# of Points (Y)"))
        self.plot_btn.setText(_translate("MainWindow", "Show"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_Scan.setTitle(_translate("MainWindow", "&Scan"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.actionContents.setText(_translate("MainWindow", "Contents"))
        self.actionSaveTask.setText(_translate("MainWindow", "Save Task"))
        self.actionLoadTask.setText(_translate("MainWindow", "Load Task"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionE_xit.setText(_translate("MainWindow", "E&xit"))
        self.actionE_xit.setShortcut(_translate("MainWindow", "Ctrl+W"))


from mpl4qt.widgets.mplerrorbarwidget import MatplotlibErrorbarWidget
from mpl4qt.widgets.mplimagewidget import MatplotlibImageWidget
from . import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
